CATEGORY_PATHS = {
    "Ankle Socks"                     : {"path": "Apparel & Accessories > Clothing > Socks > Ankle Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-1"},
    "Anklets"                         : {"path": "Apparel & Accessories > Jewelry > Anklets", "gid": "gid://shopify/TaxonomyCategory/aa-6-1"},
    "Anti Slip Steps"                 : {"path": "Apparel & Accessories > Shoe Accessories > Shoe Inserts > Anti Slip Steps", "gid": "gid://shopify/TaxonomyCategory/aa-7-5-1"},
    "Arch Supports"                   : {"path": "Apparel & Accessories > Shoe Accessories > Shoe Inserts > Arch Supports", "gid": "gid://shopify/TaxonomyCategory/aa-7-5-2"},
    "Arm Warmers & Sleeves"           : {"path": "Apparel & Accessories > Clothing Accessories > Arm Warmers & Sleeves", "gid": "gid://shopify/TaxonomyCategory/aa-2-1"},
    "Athletic Shoes"                  : {"path": "Apparel & Accessories > Shoes > Athletic Shoes", "gid": "gid://shopify/TaxonomyCategory/aa-8-1"},
    "Athletic Socks"                  : {"path": "Apparel & Accessories > Clothing > Socks > Athletic Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-2"},
    "Baby & Toddler Athletic Shoes"   : {"path": "Apparel & Accessories > Shoes > Baby & Toddler Shoes > Baby & Toddler Athletic Shoes", "gid": "gid://shopify/TaxonomyCategory/aa-8-2-4"},
    "Baby & Toddler Belts"            : {"path": "Apparel & Accessories > Clothing Accessories > Baby & Toddler Clothing Accessories > Baby & Toddler Belts", "gid": "gid://shopify/TaxonomyCategory/aa-2-2-1"},
    "Baby & Toddler Boots"            : {"path": "Apparel & Accessories > Shoes > Baby & Toddler Shoes > Baby & Toddler Boots", "gid": "gid://shopify/TaxonomyCategory/aa-8-2-1"},
    "Baby & Toddler Diaper Covers"    : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Diaper Covers", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-2"},
    "Baby & Toddler Dresses"          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-3"},
    "Baby & Toddler Gloves & Mittens" : {"path": "Apparel & Accessories > Clothing Accessories > Baby & Toddler Clothing Accessories > Baby & Toddler Gloves & Mittens", "gid": "gid://shopify/TaxonomyCategory/aa-2-2-2"},
    "Baby & Toddler Hats"             : {"path": "Apparel & Accessories > Clothing Accessories > Baby & Toddler Clothing Accessories > Baby & Toddler Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-2-3"},
    "Baby & Toddler Outfits"          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outfits", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-5"},
    "Baby & Toddler Sandals"          : {"path": "Apparel & Accessories > Shoes > Baby & Toddler Shoes > Baby & Toddler Sandals", "gid": "gid://shopify/TaxonomyCategory/aa-8-2-2"},
    "Baby & Toddler Sleepwear"        : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Sleepwear", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-6"},
    "Baby & Toddler Sneakers"         : {"path": "Apparel & Accessories > Shoes > Baby & Toddler Shoes > Baby & Toddler Sneakers", "gid": "gid://shopify/TaxonomyCategory/aa-8-2-5"},
    "Baby & Toddler Socks & Tights"   : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Socks & Tights", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-7"},
    "Baby One-Pieces"                 : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby One-Pieces", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-10"},
    "Baby Protective Wear"            : {"path": "Apparel & Accessories > Clothing Accessories > Baby & Toddler Clothing Accessories > Baby Protective Wear", "gid": "gid://shopify/TaxonomyCategory/aa-2-2-4"},
    "Badge & Pass Holders"            : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Badge & Pass Holders", "gid": "gid://shopify/TaxonomyCategory/aa-5-1"},
    "Baguette Handbags"               : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Baguette Handbags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-1"},
    "Balaclavas"                      : {"path": "Apparel & Accessories > Clothing Accessories > Balaclavas", "gid": "gid://shopify/TaxonomyCategory/aa-2-3"},
    "Bandanas & Headties"             : {"path": "Apparel & Accessories > Clothing Accessories > Bandanas & Headties", "gid": "gid://shopify/TaxonomyCategory/aa-2-4"},
    "Barrel Bags"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Barrel Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-2"},
    "Baseball Caps"                   : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Baseball Caps", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-1"},
    "Beach Bags"                      : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Beach Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-3"},
    "Beanies"                         : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Beanies", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-2"},
    "Belt Buckles"                    : {"path": "Apparel & Accessories > Clothing Accessories > Belt Buckles", "gid": "gid://shopify/TaxonomyCategory/aa-2-5"},
    "Belts"                           : {"path": "Apparel & Accessories > Clothing Accessories > Belts", "gid": "gid://shopify/TaxonomyCategory/aa-2-6"},
    "Berets"                          : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Berets", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-3"},
    "Bermudas"                        : {"path": "Apparel & Accessories > Clothing > Shorts > Bermudas", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-1"},
    "Bikinis"                         : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Underpants > Bikinis", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-2-1"},
    "Blouses"                         : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Maternity Tops > Blouses", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-8-1"},
    "Boardshorts"                     : {"path": "Apparel & Accessories > Clothing > Swimwear > Boardshorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-20-2"},
    "Body Jewelry"                    : {"path": "Apparel & Accessories > Jewelry > Body Jewelry", "gid": "gid://shopify/TaxonomyCategory/aa-6-2"},
    "Bodysuits"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Bodysuits", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-2"},
    "Bolero Jackets"                  : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Bolero Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-1"},
    "Bomber Jackets"                  : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Bomber Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-2"},
    "Boot Liners"                     : {"path": "Apparel & Accessories > Shoe Accessories > Boot Liners", "gid": "gid://shopify/TaxonomyCategory/aa-7-1"},
    "Boots"                           : {"path": "Apparel & Accessories > Shoes > Boots", "gid": "gid://shopify/TaxonomyCategory/aa-8-3"},
    "Bowler Hats"                     : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Bowler Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-4"},
    "Boxer Briefs"                    : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Toddler Underwear > Boxer Briefs", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-11-1"},
    "Boxer Shorts"                    : {"path": "Apparel & Accessories > Clothing > Boys' Underwear > Boys' Underpants > Boxer Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-3-2-2"},
    "Boxers"                          : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Loungewear > Loungewear Bottoms > Boxers", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-2-1-1"},
    "Boxing Shorts"                   : {"path": "Apparel & Accessories > Clothing > Activewear > Boxing Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-4"},
    "Boys' Long Johns"                : {"path": "Apparel & Accessories > Clothing > Boys' Underwear > Boys' Long Johns", "gid": "gid://shopify/TaxonomyCategory/aa-1-3-1"},
    "Boys' Undershirts"               : {"path": "Apparel & Accessories > Clothing > Boys' Underwear > Boys' Undershirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-3-3"},
    "Boyshorts"                       : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Underpants > Boyshorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-2-3"},
    "Bra Strap Pads"                  : {"path": "Apparel & Accessories > Clothing > Lingerie > Bra Accessories > Bra Strap Pads", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-2-1"},
    "Bra Straps & Extenders"          : {"path": "Apparel & Accessories > Clothing > Lingerie > Bra Accessories > Bra Straps & Extenders", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-2-2"},
    "Bracelets"                       : {"path": "Apparel & Accessories > Jewelry > Bracelets", "gid": "gid://shopify/TaxonomyCategory/aa-6-3"},
    "Bras"                            : {"path": "Apparel & Accessories > Clothing > Lingerie > Bras", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-3"},
    "Breast Enhancing Inserts"        : {"path": "Apparel & Accessories > Clothing > Lingerie > Bra Accessories > Breast Enhancing Inserts", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-2-3"},
    "Breast Petals & Concealers"      : {"path": "Apparel & Accessories > Clothing > Lingerie > Bra Accessories > Breast Petals & Concealers", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-2-4"},
    "Bridal Accessories"              : {"path": "Apparel & Accessories > Clothing Accessories > Bridal Accessories", "gid": "gid://shopify/TaxonomyCategory/aa-2-7"},
    "Bridal Party Dresses"            : {"path": "Apparel & Accessories > Clothing > Wedding & Bridal Party Dresses > Bridal Party Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-1-22-1"},
    "Briefs"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Toddler Underwear > Briefs", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-11-3"},
    "Brooches & Lapel Pins"           : {"path": "Apparel & Accessories > Jewelry > Brooches & Lapel Pins", "gid": "gid://shopify/TaxonomyCategory/aa-6-4"},
    "Bucket Bags"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Bucket Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-4"},
    "Bucket Hats"                     : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Bucket Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-5"},
    "Burkinis"                        : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Burkinis", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-2"},
    "Business Card Cases"             : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Business Card Cases", "gid": "gid://shopify/TaxonomyCategory/aa-5-2"},
    "Button Studs"                    : {"path": "Apparel & Accessories > Clothing Accessories > Button Studs", "gid": "gid://shopify/TaxonomyCategory/aa-2-8"},
    "Camisoles"                       : {"path": "Apparel & Accessories > Clothing > Lingerie > Camisoles", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-4"},
    "Capes"                           : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Capes", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-3"},
    "Card Cases"                      : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Card Cases", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-2"},
    "Cardigans"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Cardigans", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-3"},
    "Cargo Pants"                     : {"path": "Apparel & Accessories > Clothing > Pants > Cargo Pants", "gid": "gid://shopify/TaxonomyCategory/aa-1-12-2"},
    "Cargo Shorts"                    : {"path": "Apparel & Accessories > Clothing > Shorts > Cargo Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-2"},
    "Cargos"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Bottoms > Cargos", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-1-2"},
    "Chaps"                           : {"path": "Apparel & Accessories > Clothing > Outerwear > Chaps", "gid": "gid://shopify/TaxonomyCategory/aa-1-10-1"},
    "Charms & Pendants"               : {"path": "Apparel & Accessories > Jewelry > Charms & Pendants", "gid": "gid://shopify/TaxonomyCategory/aa-6-5"},
    "Checkbook Covers"                : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Checkbook Covers", "gid": "gid://shopify/TaxonomyCategory/aa-5-3"},
    "Chino Shorts"                    : {"path": "Apparel & Accessories > Clothing > Shorts > Chino Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-3"},
    "Chinos"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Bottoms > Chinos", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-1-3"},
    "Classic Bikinis"                 : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Classic Bikinis", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-3"},
    "Clutch Bags"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Clutch Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-5"},
    "Coin Purses"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Coin Purses", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-3"},
    "Collar Stays"                    : {"path": "Apparel & Accessories > Clothing Accessories > Collar Stays", "gid": "gid://shopify/TaxonomyCategory/aa-2-9"},
    "Contractor Pants & Coveralls"    : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Contractor Pants & Coveralls", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-1"},
    "Convertible Bags"                : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Convertible Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-6"},
    "Costume Accessories"             : {"path": "Apparel & Accessories > Costumes & Accessories > Costume Accessories", "gid": "gid://shopify/TaxonomyCategory/aa-3-1"},
    "Costume Dresses"                 : {"path": "Apparel & Accessories > Costumes & Accessories > Costumes > Costume Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-3-3-1"},
    "Costume Sets"                    : {"path": "Apparel & Accessories > Costumes & Accessories > Costumes > Costume Sets", "gid": "gid://shopify/TaxonomyCategory/aa-3-3-2"},
    "Costume Shoes"                   : {"path": "Apparel & Accessories > Costumes & Accessories > Costume Shoes", "gid": "gid://shopify/TaxonomyCategory/aa-3-2"},
    "Cover Ups"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Cover Ups", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-4"},
    "Cowboy Hats"                     : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Cowboy Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-6"},
    "Crew Socks"                      : {"path": "Apparel & Accessories > Clothing > Socks > Crew Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-3"},
    "Crop Tops"                       : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Tops > Crop Tops", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-2-1"},
    "Cross Body Bags"                 : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Cross Body Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-7"},
    "Cufflinks"                       : {"path": "Apparel & Accessories > Clothing Accessories > Cufflinks", "gid": "gid://shopify/TaxonomyCategory/aa-2-10"},
    "Dance Dresses, Skirts & Costumes": {"path": "Apparel & Accessories > Clothing > Activewear > Dance Dresses, Skirts & Costumes", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-5"},
    "Dance Socks"                     : {"path": "Apparel & Accessories > Clothing > Socks > Dance Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-4"},
    "Decorative Fans"                 : {"path": "Apparel & Accessories > Clothing Accessories > Decorative Fans", "gid": "gid://shopify/TaxonomyCategory/aa-2-11"},
    "Denim Shorts"                    : {"path": "Apparel & Accessories > Clothing > Shorts > Denim Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-5"},
    "Doctor Bags"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Doctor Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-8"},
    "Dresses"                         : {"path": "Apparel & Accessories > Clothing > Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-1-4"},
    "Earmuffs"                        : {"path": "Apparel & Accessories > Clothing Accessories > Earmuffs", "gid": "gid://shopify/TaxonomyCategory/aa-2-12"},
    "Earrings"                        : {"path": "Apparel & Accessories > Jewelry > Earrings", "gid": "gid://shopify/TaxonomyCategory/aa-6-6"},
    "Envelope Clutches"               : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Envelope Clutches", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-9"},
    "Fascinators"                     : {"path": "Apparel & Accessories > Clothing Accessories > Headwear > Fascinators", "gid": "gid://shopify/TaxonomyCategory/aa-2-18-1"},
    "Fashion Face Masks"              : {"path": "Apparel & Accessories > Clothing Accessories > Fashion Face Masks", "gid": "gid://shopify/TaxonomyCategory/aa-2-32"},
    "Fedoras"                         : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Fedoras", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-7"},
    "First Bras"                      : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Undershirts > First Bras", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-3-2"},
    "First Steps & Crawlers"          : {"path": "Apparel & Accessories > Shoes > Baby & Toddler Shoes > First Steps & Crawlers", "gid": "gid://shopify/TaxonomyCategory/aa-8-2-6"},
    "Flat Caps"                       : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Flat Caps", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-8"},
    "Flats"                           : {"path": "Apparel & Accessories > Shoes > Flats", "gid": "gid://shopify/TaxonomyCategory/aa-8-9"},
    "Flight Suits"                    : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Flight Suits", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-2"},
    "Fold Over Clutches"              : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Fold Over Clutches", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-10"},
    "Food Service Uniforms"           : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Food Service Uniforms", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-3"},
    "Footie Socks"                    : {"path": "Apparel & Accessories > Clothing > Socks > Footie Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-5"},
    "Full Body Shapes"                : {"path": "Apparel & Accessories > Clothing > Lingerie > Shapewear > Full Body Shapes", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-10-2"},
    "G-Strings"                       : {"path": "Apparel & Accessories > Clothing > Lingerie > Women's Underpants > G-Strings", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-11-4"},
    "Gaiters"                         : {"path": "Apparel & Accessories > Shoe Accessories > Gaiters", "gid": "gid://shopify/TaxonomyCategory/aa-7-2"},
    "Garter Belts"                    : {"path": "Apparel & Accessories > Clothing > Lingerie > Lingerie Accessories > Garter Belts", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-8-1"},
    "Garters"                         : {"path": "Apparel & Accessories > Clothing > Lingerie > Lingerie Accessories > Garters", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-8-2"},
    "Gel Pads"                        : {"path": "Apparel & Accessories > Shoe Accessories > Shoe Inserts > Gel Pads", "gid": "gid://shopify/TaxonomyCategory/aa-7-5-3"},
    "Girls' Long Johns"               : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Long Johns", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-1"},
    "Gloves & Mittens"                : {"path": "Apparel & Accessories > Clothing Accessories > Gloves & Mittens", "gid": "gid://shopify/TaxonomyCategory/aa-2-13"},
    "Hair Bands"                      : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Bands", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-13"},
    "Hair Bun & Volume Shapers"       : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Bun & Volume Shapers", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-1"},
    "Hair Combs"                      : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Combs", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-2"},
    "Hair Extensions"                 : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Extensions", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-3"},
    "Hair Forks & Sticks"             : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Forks & Sticks", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-4"},
    "Hair Nets"                       : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Nets", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-5"},
    "Hair Pins, Claws & Clips"        : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Pins, Claws & Clips", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-6"},
    "Hair Wreaths"                    : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Wreaths", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-7"},
    "Half-Moon Bags"                  : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Half-Moon Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-11"},
    "Hand Muffs"                      : {"path": "Apparel & Accessories > Clothing Accessories > Hand Muffs", "gid": "gid://shopify/TaxonomyCategory/aa-2-15"},
    "Handkerchiefs"                   : {"path": "Apparel & Accessories > Clothing Accessories > Handkerchiefs", "gid": "gid://shopify/TaxonomyCategory/aa-2-16"},
    "Headbands"                       : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Headbands", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-8"},
    "Headdresses"                     : {"path": "Apparel & Accessories > Clothing Accessories > Headwear > Headdresses", "gid": "gid://shopify/TaxonomyCategory/aa-2-18-2"},
    "Heel Cushions"                   : {"path": "Apparel & Accessories > Shoe Accessories > Shoe Inserts > Heel Cushions", "gid": "gid://shopify/TaxonomyCategory/aa-7-5-4"},
    "Heel Socks"                      : {"path": "Apparel & Accessories > Clothing > Socks > Heel Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-6"},
    "Heels"                           : {"path": "Apparel & Accessories > Shoes > Heels", "gid": "gid://shopify/TaxonomyCategory/aa-8-10"},
    "High Waisted Briefs"             : {"path": "Apparel & Accessories > Clothing > Lingerie > Shapewear > High Waisted Briefs", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-10-3"},
    "Hipsters"                        : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Underpants > Hipsters", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-2-5"},
    "Hobo Bags"                       : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Hobo Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-12"},
    "Hold Up Socks"                   : {"path": "Apparel & Accessories > Clothing > Socks > Hold Up Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-7"},
    "Hoodies"                         : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Sweatshirts & Hoodies > Hoodies", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-7-2"},
    "Hosiery"                         : {"path": "Apparel & Accessories > Clothing > Lingerie > Hosiery", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-6"},
    "Jackets"                         : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Vests & Jackets > Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-8-2"},
    "Jeans"                           : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Bottoms > Jeans", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-1-4"},
    "Jegging Shorts"                  : {"path": "Apparel & Accessories > Clothing > Shorts > Jegging Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-6"},
    "Jeggings"                        : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Bottoms > Jeggings", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-1-5"},
    "Jewelry Sets"                    : {"path": "Apparel & Accessories > Jewelry > Jewelry Sets", "gid": "gid://shopify/TaxonomyCategory/aa-6-7"},
    "Jock Straps"                     : {"path": "Apparel & Accessories > Clothing > Lingerie > Jock Straps", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-7"},
    "Jockstraps"                      : {"path": "Apparel & Accessories > Clothing > Men's Undergarments > Men's Underwear > Jockstraps", "gid": "gid://shopify/TaxonomyCategory/aa-1-8-3-5"},
    "Jogger Shorts"                   : {"path": "Apparel & Accessories > Clothing > Shorts > Jogger Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-7"},
    "Joggers"                         : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Loungewear > Loungewear Bottoms > Joggers", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-2-1-2"},
    "Key Cases"                       : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Key Cases", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-4"},
    "Keychains"                       : {"path": "Apparel & Accessories > Handbag & Wallet Accessories > Keychains", "gid": "gid://shopify/TaxonomyCategory/aa-4-1"},
    "Kimonos"                         : {"path": "Apparel & Accessories > Clothing > Traditional & Ceremonial Clothing > Kimonos", "gid": "gid://shopify/TaxonomyCategory/aa-1-23-1"},
    "Knee Socks"                      : {"path": "Apparel & Accessories > Clothing > Socks > Knee Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-8"},
    "Lanyards"                        : {"path": "Apparel & Accessories > Handbag & Wallet Accessories > Lanyards", "gid": "gid://shopify/TaxonomyCategory/aa-4-2"},
    "Leg Warmers"                     : {"path": "Apparel & Accessories > Clothing Accessories > Leg Warmers", "gid": "gid://shopify/TaxonomyCategory/aa-2-19"},
    "Legging Shorts"                  : {"path": "Apparel & Accessories > Clothing > Shorts > Legging Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-8"},
    "Leggings"                        : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Loungewear > Loungewear Bottoms > Leggings", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-2-1-3"},
    "Leis"                            : {"path": "Apparel & Accessories > Clothing Accessories > Leis", "gid": "gid://shopify/TaxonomyCategory/aa-2-20"},
    "Leotards & Unitards"             : {"path": "Apparel & Accessories > Clothing > Activewear > Leotards & Unitards", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-9"},
    "Long Johns"                      : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Long Johns", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-1"},
    "Loungewear Tops"                 : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Loungewear > Loungewear Tops", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-2-2"},
    "Masks"                           : {"path": "Apparel & Accessories > Costumes & Accessories > Masks", "gid": "gid://shopify/TaxonomyCategory/aa-3-4"},
    "Maternity Belts & Support Bands" : {"path": "Apparel & Accessories > Clothing Accessories > Maternity Belts & Support Bands", "gid": "gid://shopify/TaxonomyCategory/aa-2-21"},
    "Maternity Dresses"               : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Maternity Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-2"},
    "Maternity One-Pieces"            : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Maternity One-Pieces", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-3"},
    "Maternity Skirts"                : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Maternity Skirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-5"},
    "Maternity Sleepwear"             : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Maternity Sleepwear", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-6"},
    "Men's Long Johns"                : {"path": "Apparel & Accessories > Clothing > Men's Undergarments > Men's Long Johns", "gid": "gid://shopify/TaxonomyCategory/aa-1-8-1"},
    "Men's Undershirts"               : {"path": "Apparel & Accessories > Clothing > Men's Undergarments > Men's Undershirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-8-2"},
    "Midway Briefs"                   : {"path": "Apparel & Accessories > Clothing > Boys' Underwear > Boys' Underpants > Midway Briefs", "gid": "gid://shopify/TaxonomyCategory/aa-1-3-2-4"},
    "Military Uniforms"               : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Military Uniforms", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-4"},
    "Minaudieres"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Minaudieres", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-13"},
    "Motorcycle Outerwear"            : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Motorcycle Outerwear", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-4"},
    "Muff Clutches & Bags"            : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Muff Clutches & Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-14"},
    "Neck Gaiters"                    : {"path": "Apparel & Accessories > Clothing Accessories > Neck Gaiters", "gid": "gid://shopify/TaxonomyCategory/aa-2-22"},
    "Neck Pouches"                    : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Neck Pouches", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-5"},
    "Necklaces"                       : {"path": "Apparel & Accessories > Jewelry > Necklaces", "gid": "gid://shopify/TaxonomyCategory/aa-6-8"},
    "Neckties"                        : {"path": "Apparel & Accessories > Clothing Accessories > Neckties", "gid": "gid://shopify/TaxonomyCategory/aa-2-23"},
    "Nightgowns"                      : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Nightgowns", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-3"},
    "Nursing Bras"                    : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Nursing Bras", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-1"},
    "Nursing Shirts"                  : {"path": "Apparel & Accessories > Clothing > Maternity Clothing > Maternity Tops > Nursing Shirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-7-8-4"},
    "One-Piece Swimsuits"             : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > One-Piece Swimsuits", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-22"},
    "One-Pieces"                      : {"path": "Apparel & Accessories > Clothing > One-Pieces", "gid": "gid://shopify/TaxonomyCategory/aa-1-9"},
    "Onesies"                         : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Onesies", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-6"},
    "Outfit Sets"                     : {"path": "Apparel & Accessories > Clothing > Outfit Sets", "gid": "gid://shopify/TaxonomyCategory/aa-1-11"},
    "Overcoats"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Overcoats", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-5"},
    "Overshirts"                      : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Overshirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-4"},
    "Pajamas"                         : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Pajamas", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-4"},
    "Panama Hats"                     : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Panama Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-9"},
    "Pant Suits"                      : {"path": "Apparel & Accessories > Clothing > Suits > Pant Suits", "gid": "gid://shopify/TaxonomyCategory/aa-1-19-1"},
    "Panties"                         : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Toddler Underwear > Panties", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-11-4"},
    "Panty Socks"                     : {"path": "Apparel & Accessories > Clothing > Socks > Panty Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-9"},
    "Pantyhose"                       : {"path": "Apparel & Accessories > Clothing > Lingerie > Lingerie Accessories > Pantyhose", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-8-3"},
    "Parkas"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Parkas", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-6"},
    "Pea Coats"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Pea Coats", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-7"},
    "Period Underwear"                : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Underpants > Period Underwear", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-2-7"},
    "Petticoats & Pettipants"         : {"path": "Apparel & Accessories > Clothing > Lingerie > Petticoats & Pettipants", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-9"},
    "Pinback Buttons"                 : {"path": "Apparel & Accessories > Clothing Accessories > Pinback Buttons", "gid": "gid://shopify/TaxonomyCategory/aa-2-24"},
    "Polos"                           : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Polos", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-5"},
    "Ponchos"                         : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Ponchos", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-8"},
    "Ponytail Holders"                : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Ponytail Holders", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-9"},
    "Puffer Jackets"                  : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Puffer Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-9"},
    "Rain Coats"                      : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Rain Coats", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-10"},
    "Rain Pants"                      : {"path": "Apparel & Accessories > Clothing > Outerwear > Rain Pants", "gid": "gid://shopify/TaxonomyCategory/aa-1-10-3"},
    "Rain Suits"                      : {"path": "Apparel & Accessories > Clothing > Outerwear > Rain Suits", "gid": "gid://shopify/TaxonomyCategory/aa-1-10-4"},
    "Rash Guards"                     : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Rash Guards", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-9"},
    "Rings"                           : {"path": "Apparel & Accessories > Jewelry > Rings", "gid": "gid://shopify/TaxonomyCategory/aa-6-9"},
    "Robes"                           : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Robes", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-5"},
    "Saddle Bags"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Saddle Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-15"},
    "Sandals"                         : {"path": "Apparel & Accessories > Shoes > Sandals", "gid": "gid://shopify/TaxonomyCategory/aa-8-6"},
    "Saris & Lehengas"                : {"path": "Apparel & Accessories > Clothing > Traditional & Ceremonial Clothing > Saris & Lehengas", "gid": "gid://shopify/TaxonomyCategory/aa-1-23-2"},
    "Sashes"                          : {"path": "Apparel & Accessories > Clothing Accessories > Sashes", "gid": "gid://shopify/TaxonomyCategory/aa-2-25"},
    "Satchel Bags"                    : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Satchel Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-16"},
    "Scarves & Shawls"                : {"path": "Apparel & Accessories > Clothing Accessories > Scarves & Shawls", "gid": "gid://shopify/TaxonomyCategory/aa-2-26"},
    "School Bags"                     : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > School Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-17"},
    "School Uniforms"                 : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > School Uniforms", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-5"},
    "Scrubs"                          : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Scrubs", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-9"},
    "Security Uniforms"               : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Security Uniforms", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-6"},
    "Shirts"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Shirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-6"},
    "Shoe Covers"                     : {"path": "Apparel & Accessories > Shoe Accessories > Shoe Covers", "gid": "gid://shopify/TaxonomyCategory/aa-7-3"},
    "Shoe Grips"                      : {"path": "Apparel & Accessories > Shoe Accessories > Shoe Grips", "gid": "gid://shopify/TaxonomyCategory/aa-7-4"},
    "Shoelaces"                       : {"path": "Apparel & Accessories > Shoe Accessories > Shoelaces", "gid": "gid://shopify/TaxonomyCategory/aa-7-6"},
    "Shopper Bags"                    : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Shopper Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-18"},
    "Short Trousers"                  : {"path": "Apparel & Accessories > Clothing > Shorts > Short Trousers", "gid": "gid://shopify/TaxonomyCategory/aa-1-14-4"},
    "Shorts"                          : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Loungewear > Loungewear Bottoms > Shorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-2-1-4"},
    "Shoulder Bags"                   : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Shoulder Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-19"},
    "Skirt Suits"                     : {"path": "Apparel & Accessories > Clothing > Suits > Skirt Suits", "gid": "gid://shopify/TaxonomyCategory/aa-1-19-2"},
    "Skirtinis"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Skirtinis", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-10"},
    "Skirts"                          : {"path": "Apparel & Accessories > Clothing > Sleepwear & Loungewear > Loungewear > Loungewear Bottoms > Skirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-17-2-1-5"},
    "Skorts"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Bottoms > Skorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-1-12"},
    "Slippers"                        : {"path": "Apparel & Accessories > Shoes > Slippers", "gid": "gid://shopify/TaxonomyCategory/aa-8-7"},
    "Smart Watches"                   : {"path": "Apparel & Accessories > Jewelry > Smart Watches", "gid": "gid://shopify/TaxonomyCategory/aa-6-12"},
    "Snapback Caps"                   : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Snapback Caps", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-10"},
    "Sneaker Socks"                   : {"path": "Apparel & Accessories > Clothing > Socks > Sneaker Socks", "gid": "gid://shopify/TaxonomyCategory/aa-1-18-10"},
    "Sneakers"                        : {"path": "Apparel & Accessories > Shoes > Sneakers", "gid": "gid://shopify/TaxonomyCategory/aa-8-8"},
    "Snow Pants & Suits"              : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Snow Pants & Suits", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-18"},
    "Sport Jackets"                   : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Sport Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-11"},
    "Sports Bras"                     : {"path": "Apparel & Accessories > Clothing > Activewear > Sports Bras", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-6"},
    "Sports Uniforms"                 : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > Sports Uniforms", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-7"},
    "Spurs"                           : {"path": "Apparel & Accessories > Shoe Accessories > Spurs", "gid": "gid://shopify/TaxonomyCategory/aa-7-7"},
    "Sun Hats"                        : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Sun Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-11"},
    "Sunglasses"                      : {"path": "Apparel & Accessories > Clothing Accessories > Sunglasses", "gid": "gid://shopify/TaxonomyCategory/aa-2-27"},
    "Surf Tops"                       : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Surf Tops", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-23"},
    "Suspenders"                      : {"path": "Apparel & Accessories > Clothing Accessories > Suspenders", "gid": "gid://shopify/TaxonomyCategory/aa-2-28"},
    "Sweaters"                        : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Sweaters", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-12"},
    "Sweatpants"                      : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Pants > Sweatpants", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-1-4"},
    "Sweatshirts"                     : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Sweatshirts & Hoodies > Sweatshirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-7-4"},
    "Swim Boxers"                     : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Swim Boxers", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-13"},
    "Swim Briefs"                     : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Swim Briefs", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-14"},
    "Swim Dresses"                    : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Swim Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-15"},
    "Swim Jammers"                    : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Swim Jammers", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-16"},
    "Swim Trunks"                     : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Swim Trunks", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-17"},
    "Swimwear Tops"                   : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Swimwear > Swimwear Tops", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-8-24"},
    "T-Shirts"                        : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Tops > T-Shirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-2-2"},
    "Tank Tops"                       : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Tops > Tank Tops", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-2-3"},
    "Thigh Slimmers"                  : {"path": "Apparel & Accessories > Clothing > Lingerie > Shapewear > Thigh Slimmers", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-10-4"},
    "Thongs"                          : {"path": "Apparel & Accessories > Clothing > Girls' Underwear > Girls' Underpants > Thongs", "gid": "gid://shopify/TaxonomyCategory/aa-1-5-2-8"},
    "Tiaras"                          : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Tiaras", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-10"},
    "Tie Clips"                       : {"path": "Apparel & Accessories > Clothing Accessories > Tie Clips", "gid": "gid://shopify/TaxonomyCategory/aa-2-29"},
    "Tights"                          : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Pants > Tights", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-1-5"},
    "Top Hats"                        : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Top Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-12"},
    "Track Jackets"                   : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Track Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-12"},
    "Track Pants"                     : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Pants > Track Pants", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-1-6"},
    "Traditional Clothing Accessories": {"path": "Apparel & Accessories > Clothing Accessories > Traditional Clothing Accessories", "gid": "gid://shopify/TaxonomyCategory/aa-2-31"},
    "Training Pants"                  : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Pants > Training Pants", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-1-7"},
    "Trapezoid Bags"                  : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Handbags > Trapezoid Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-4-20"},
    "Travel Wallets"                  : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Travel Wallets", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-6"},
    "Trench Coats"                    : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Trench Coats", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-13"},
    "Trilbies"                        : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Trilbies", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-13"},
    "Trousers"                        : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Bottoms > Trousers", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-1-14"},
    "Trucker Hats"                    : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Trucker Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-14"},
    "Trucker Jackets"                 : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Trucker Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-14"},
    "Trunks"                          : {"path": "Apparel & Accessories > Clothing > Boys' Underwear > Boys' Underpants > Trunks", "gid": "gid://shopify/TaxonomyCategory/aa-1-3-2-5"},
    "Tunics"                          : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Tops > Tunics", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-9-10"},
    "Turbans"                         : {"path": "Apparel & Accessories > Clothing Accessories > Headwear > Turbans", "gid": "gid://shopify/TaxonomyCategory/aa-2-18-3"},
    "Tuxedos"                         : {"path": "Apparel & Accessories > Clothing > Suits > Tuxedos", "gid": "gid://shopify/TaxonomyCategory/aa-1-19-3"},
    "Undershorts"                     : {"path": "Apparel & Accessories > Clothing > Men's Undergarments > Men's Underwear > Undershorts", "gid": "gid://shopify/TaxonomyCategory/aa-1-8-3-9"},
    "Varsity Jackets"                 : {"path": "Apparel & Accessories > Clothing > Outerwear > Coats & Jackets > Varsity Jackets", "gid": "gid://shopify/TaxonomyCategory/aa-1-10-2-15"},
    "Vests"                           : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Vests & Jackets > Vests", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-8-1"},
    "Visors"                          : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Visors", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-15"},
    "Waist Cinchers"                  : {"path": "Apparel & Accessories > Clothing > Lingerie > Shapewear > Waist Cinchers", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-10-5"},
    "Wallet Chains"                   : {"path": "Apparel & Accessories > Handbag & Wallet Accessories > Wallet Chains", "gid": "gid://shopify/TaxonomyCategory/aa-4-3"},
    "Wallets"                         : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Wallets", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-7"},
    "Watch Bands"                     : {"path": "Apparel & Accessories > Jewelry > Watch Accessories > Watch Bands", "gid": "gid://shopify/TaxonomyCategory/aa-6-10-1"},
    "Watch Stickers & Decals"         : {"path": "Apparel & Accessories > Jewelry > Watch Accessories > Watch Stickers & Decals", "gid": "gid://shopify/TaxonomyCategory/aa-6-10-2"},
    "Watch Winders"                   : {"path": "Apparel & Accessories > Jewelry > Watch Accessories > Watch Winders", "gid": "gid://shopify/TaxonomyCategory/aa-6-10-3"},
    "Watches"                         : {"path": "Apparel & Accessories > Jewelry > Watches", "gid": "gid://shopify/TaxonomyCategory/aa-6-11"},
    "Wedding Dresses"                 : {"path": "Apparel & Accessories > Clothing > Wedding & Bridal Party Dresses > Wedding Dresses", "gid": "gid://shopify/TaxonomyCategory/aa-1-22-2"},
    "White Coats"                     : {"path": "Apparel & Accessories > Clothing > Uniforms & Workwear > White Coats", "gid": "gid://shopify/TaxonomyCategory/aa-1-24-8"},
    "Wig Accessories"                 : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Wig Accessories", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-11"},
    "Wigs"                            : {"path": "Apparel & Accessories > Clothing Accessories > Hair Accessories > Wigs", "gid": "gid://shopify/TaxonomyCategory/aa-2-14-12"},
    "Wind Pants"                      : {"path": "Apparel & Accessories > Clothing > Activewear > Activewear Pants > Wind Pants", "gid": "gid://shopify/TaxonomyCategory/aa-1-1-1-8"},
    "Windbreakers"                    : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Windbreakers", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-15"},
    "Winter Hats"                     : {"path": "Apparel & Accessories > Clothing Accessories > Hats > Winter Hats", "gid": "gid://shopify/TaxonomyCategory/aa-2-17-16"},
    "Women's Undershirts"             : {"path": "Apparel & Accessories > Clothing > Lingerie > Women's Undershirts", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-12"},
    "Women's Underwear Slips"         : {"path": "Apparel & Accessories > Clothing > Lingerie > Women's Underwear Slips", "gid": "gid://shopify/TaxonomyCategory/aa-1-6-13"},
    "Wrap Coats"                      : {"path": "Apparel & Accessories > Clothing > Baby & Toddler Clothing > Baby & Toddler Outerwear > Baby & Toddler Coats & Jackets > Wrap Coats", "gid": "gid://shopify/TaxonomyCategory/aa-1-2-4-17-16"},
    "Wrist Bags"                      : {"path": "Apparel & Accessories > Handbags, Wallets & Cases > Wallets & Money Clips > Wrist Bags", "gid": "gid://shopify/TaxonomyCategory/aa-5-5-8"},
    "Wristbands"                      : {"path": "Apparel & Accessories > Clothing Accessories > Wristbands", "gid": "gid://shopify/TaxonomyCategory/aa-2-30"},
}