import re

ATTRIBUTE_PATTERNS = {
  "size": {
    "0": "\\b0s?\\b",
    "0-3 months": "\\b03[\\s\\-]?monthss?\\b",
    "00": "\\b00s?\\b",
    "000": "\\b000s?\\b",
    "1": "\\b1s?\\b",
    "10": "\\b10s?\\b",
    "12": "\\b12s?\\b",
    "12-18 months": "\\b1218[\\s\\-]?monthss?\\b",
    "14": "\\b14s?\\b",
    "16": "\\b16s?\\b",
    "18": "\\b18s?\\b",
    "18-24 months": "\\b1824[\\s\\-]?monthss?\\b",
    "2": "\\b2s?\\b",
    "2-3 years": "\\b23[\\s\\-]?yearss?\\b",
    "20": "\\b20s?\\b",
    "22": "\\b22s?\\b",
    "24": "\\b24s?\\b",
    "26": "\\b26s?\\b",
    "28": "\\b28s?\\b",
    "3-4 years": "\\b34[\\s\\-]?yearss?\\b",
    "3-6 months": "\\b36[\\s\\-]?monthss?\\b",
    "30": "\\b30s?\\b",
    "32": "\\b32s?\\b",
    "34": "\\b34s?\\b",
    "36": "\\b36s?\\b",
    "38": "\\b38s?\\b",
    "4": "\\b4s?\\b",
    "4-5 years": "\\b45[\\s\\-]?yearss?\\b",
    "40": "\\b40s?\\b",
    "42": "\\b42s?\\b",
    "44": "\\b44s?\\b",
    "46": "\\b46s?\\b",
    "48": "\\b48s?\\b",
    "5-6 years": "\\b56[\\s\\-]?yearss?\\b",
    "50": "\\b50s?\\b",
    "52": "\\b52s?\\b",
    "54": "\\b54s?\\b",
    "56": "\\b56s?\\b",
    "58": "\\b58s?\\b",
    "6": "\\b6s?\\b",
    "6-9 months": "\\b69[\\s\\-]?monthss?\\b",
    "60": "\\b60s?\\b",
    "8": "\\b8s?\\b",
    "9-12 months": "\\b912[\\s\\-]?monthss?\\b",
    "Double extra large (XXL)": "\\bdouble[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?xxls?\\b",
    "Double extra small (XXS)": "\\bdouble[\\s\\-]?extra[\\s\\-]?small[\\s\\-]?xxss?\\b",
    "Extra large (XL)": "\\bextra[\\s\\-]?large[\\s\\-]?xls?\\b",
    "Extra small (XS)": "\\bextra[\\s\\-]?small[\\s\\-]?xss?\\b",
    "Five extra large (5XL)": "\\bfive[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?5xls?\\b",
    "Four extra large (4XL)": "\\bfour[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?4xls?\\b",
    "Large (L)": "\\blarge[\\s\\-]?ls?\\b",
    "Medium (M)": "\\bmedium[\\s\\-]?ms?\\b",
    "One size": "\\bone[\\s\\-]?sizes?\\b",
    "Six extra large (6XL)": "\\bsix[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?6xls?\\b",
    "Small (S)": "\\bsmall[\\s\\-]?ss?\\b",
    "Triple extra large (XXXL)": "\\btriple[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?xxxls?\\b",
    "Triple extra small (XXXS)": "\\btriple[\\s\\-]?extra[\\s\\-]?small[\\s\\-]?xxxss?\\b",
    "Other": "\\bothers?\\b"
  },
  "shoe-size": {
    "0": "\\b0s?\\b",
    "0.5": "\\b05s?\\b",
    "1": "\\b1s?\\b",
    "1.5": "\\b15s?\\b",
    "10": "\\b10s?\\b",
    "10.5": "\\b105s?\\b",
    "11": "\\b11s?\\b",
    "11.5": "\\b115s?\\b",
    "12": "\\b12s?\\b",
    "12.5": "\\b125s?\\b",
    "13": "\\b13s?\\b",
    "13.5": "\\b135s?\\b",
    "14": "\\b14s?\\b",
    "14.5": "\\b145s?\\b",
    "15": "\\b15s?\\b",
    "15.5": "\\b155s?\\b",
    "16": "\\b16s?\\b",
    "16.5": "\\b165s?\\b",
    "17": "\\b17s?\\b",
    "17.5": "\\b175s?\\b",
    "18": "\\b18s?\\b",
    "18.5": "\\b185s?\\b",
    "19": "\\b19s?\\b",
    "19.5": "\\b195s?\\b",
    "2": "\\b2s?\\b",
    "2.5": "\\b25s?\\b",
    "20": "\\b20s?\\b",
    "20.5": "\\b205s?\\b",
    "21": "\\b21s?\\b",
    "21.5": "\\b215s?\\b",
    "22": "\\b22s?\\b",
    "22.5": "\\b225s?\\b",
    "23": "\\b23s?\\b",
    "23.5": "\\b235s?\\b",
    "24": "\\b24s?\\b",
    "24.5": "\\b245s?\\b",
    "25": "\\b25s?\\b",
    "25.5": "\\b255s?\\b",
    "26": "\\b26s?\\b",
    "26.5": "\\b265s?\\b",
    "27": "\\b27s?\\b",
    "27.5": "\\b275s?\\b",
    "28": "\\b28s?\\b",
    "28.5": "\\b285s?\\b",
    "29": "\\b29s?\\b",
    "29.5": "\\b295s?\\b",
    "3": "\\b3s?\\b",
    "3.5": "\\b35s?\\b",
    "30": "\\b30s?\\b",
    "30.5": "\\b305s?\\b",
    "31": "\\b31s?\\b",
    "31.5": "\\b315s?\\b",
    "32": "\\b32s?\\b",
    "32.5": "\\b325s?\\b",
    "33": "\\b33s?\\b",
    "33.5": "\\b335s?\\b",
    "34": "\\b34s?\\b",
    "34.5": "\\b345s?\\b",
    "35": "\\b35s?\\b",
    "35.5": "\\b355s?\\b",
    "36": "\\b36s?\\b",
    "36.5": "\\b365s?\\b",
    "37": "\\b37s?\\b",
    "37.5": "\\b375s?\\b",
    "38": "\\b38s?\\b",
    "38.5": "\\b385s?\\b",
    "39": "\\b39s?\\b",
    "39.5": "\\b395s?\\b",
    "4": "\\b4s?\\b",
    "4.5": "\\b45s?\\b",
    "40": "\\b40s?\\b",
    "40.5": "\\b405s?\\b",
    "41": "\\b41s?\\b",
    "41.5": "\\b415s?\\b",
    "42": "\\b42s?\\b",
    "42.5": "\\b425s?\\b",
    "43": "\\b43s?\\b",
    "43.5": "\\b435s?\\b",
    "44": "\\b44s?\\b",
    "44.5": "\\b445s?\\b",
    "45": "\\b45s?\\b",
    "45.5": "\\b455s?\\b",
    "46": "\\b46s?\\b",
    "46.5": "\\b465s?\\b",
    "47": "\\b47s?\\b",
    "47.5": "\\b475s?\\b",
    "48": "\\b48s?\\b",
    "48.5": "\\b485s?\\b",
    "49": "\\b49s?\\b",
    "49.5": "\\b495s?\\b",
    "5": "\\b5s?\\b",
    "5.5": "\\b55s?\\b",
    "50": "\\b50s?\\b",
    "50.5": "\\b505s?\\b",
    "51": "\\b51s?\\b",
    "51.5": "\\b515s?\\b",
    "52": "\\b52s?\\b",
    "52.5": "\\b525s?\\b",
    "53": "\\b53s?\\b",
    "53.5": "\\b535s?\\b",
    "54": "\\b54s?\\b",
    "54.5": "\\b545s?\\b",
    "55": "\\b55s?\\b",
    "55.5": "\\b555s?\\b",
    "56": "\\b56s?\\b",
    "56.5": "\\b565s?\\b",
    "57": "\\b57s?\\b",
    "57.5": "\\b575s?\\b",
    "58": "\\b58s?\\b",
    "58.5": "\\b585s?\\b",
    "59": "\\b59s?\\b",
    "59.5": "\\b595s?\\b",
    "6": "\\b6s?\\b",
    "6.5": "\\b65s?\\b",
    "60": "\\b60s?\\b",
    "7": "\\b7s?\\b",
    "7.5": "\\b75s?\\b",
    "8": "\\b8s?\\b",
    "8.5": "\\b85s?\\b",
    "9": "\\b9s?\\b",
    "9.5": "\\b95s?\\b",
    "Double extra large (XXL)": "\\bdouble[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?xxls?\\b",
    "Extra large (XL)": "\\bextra[\\s\\-]?large[\\s\\-]?xls?\\b",
    "Extra small (XS)": "\\bextra[\\s\\-]?small[\\s\\-]?xss?\\b",
    "Large (L)": "\\blarge[\\s\\-]?ls?\\b",
    "Medium (M)": "\\bmedium[\\s\\-]?ms?\\b",
    "Small (S)": "\\bsmall[\\s\\-]?ss?\\b",
    "Triple extra large (XXXL)": "\\btriple[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?xxxls?\\b",
    "Other": "\\bothers?\\b"
  },
  "age-group": {
    "0-6 months": "\\b06[\\s\\-]?monthss?\\b",
    "1-2 years": "\\b12[\\s\\-]?yearss?\\b",
    "6-12 months": "\\b612[\\s\\-]?monthss?\\b",
    "Adults": "\\badultss?\\b",
    "All ages": "\\ball[\\s\\-]?agess?\\b",
    "Babies": "\\bbabiess?\\b",
    "Kids": "\\bkidss?\\b",
    "Newborn": "\\bnewborns?\\b",
    "Teens": "\\bteenss?\\b",
    "Toddlers": "\\btoddlerss?\\b",
    "Universal": "\\buniversals?\\b",
    "Other": "\\bothers?\\b"
  },
  "ring-size": {
    "0.5": "\\b05s?\\b",
    "1": "\\b1s?\\b",
    "1.5": "\\b15s?\\b",
    "10": "\\b10s?\\b",
    "10.5": "\\b105s?\\b",
    "11": "\\b11s?\\b",
    "11.5": "\\b115s?\\b",
    "12": "\\b12s?\\b",
    "12.5": "\\b125s?\\b",
    "13": "\\b13s?\\b",
    "2": "\\b2s?\\b",
    "2.5": "\\b25s?\\b",
    "3": "\\b3s?\\b",
    "3.5": "\\b35s?\\b",
    "38": "\\b38s?\\b",
    "39": "\\b39s?\\b",
    "4": "\\b4s?\\b",
    "4.5": "\\b45s?\\b",
    "40": "\\b40s?\\b",
    "41": "\\b41s?\\b",
    "42": "\\b42s?\\b",
    "43": "\\b43s?\\b",
    "44": "\\b44s?\\b",
    "45": "\\b45s?\\b",
    "46": "\\b46s?\\b",
    "47": "\\b47s?\\b",
    "48": "\\b48s?\\b",
    "49": "\\b49s?\\b",
    "5": "\\b5s?\\b",
    "5.5": "\\b55s?\\b",
    "50": "\\b50s?\\b",
    "51": "\\b51s?\\b",
    "52": "\\b52s?\\b",
    "53": "\\b53s?\\b",
    "54": "\\b54s?\\b",
    "55": "\\b55s?\\b",
    "56": "\\b56s?\\b",
    "57": "\\b57s?\\b",
    "58": "\\b58s?\\b",
    "59": "\\b59s?\\b",
    "6": "\\b6s?\\b",
    "6.5": "\\b65s?\\b",
    "60": "\\b60s?\\b",
    "61": "\\b61s?\\b",
    "62": "\\b62s?\\b",
    "63": "\\b63s?\\b",
    "64": "\\b64s?\\b",
    "65": "\\b65s?\\b",
    "66": "\\b66s?\\b",
    "67": "\\b67s?\\b",
    "68": "\\b68s?\\b",
    "69": "\\b69s?\\b",
    "7": "\\b7s?\\b",
    "7.5": "\\b75s?\\b",
    "8": "\\b8s?\\b",
    "8.5": "\\b85s?\\b",
    "9": "\\b9s?\\b",
    "9.5": "\\b95s?\\b",
    "A": "\\bas?\\b",
    "B": "\\bbs?\\b",
    "C": "\\bcs?\\b",
    "D": "\\bds?\\b",
    "E": "\\bes?\\b",
    "F": "\\bfs?\\b",
    "G": "\\bgs?\\b",
    "H": "\\bhs?\\b",
    "I": "\\bis?\\b",
    "J": "\\bjs?\\b",
    "K": "\\bks?\\b",
    "L": "\\bls?\\b",
    "M": "\\bms?\\b",
    "N": "\\bns?\\b",
    "O": "\\bos?\\b",
    "P": "\\bps?\\b",
    "Q": "\\bqs?\\b",
    "R": "\\brs?\\b",
    "S": "\\bss?\\b",
    "T": "\\bts?\\b",
    "U": "\\bus?\\b",
    "V": "\\bvs?\\b",
    "W": "\\bws?\\b",
    "X": "\\bxs?\\b",
    "Y": "\\bys?\\b",
    "Z": "\\bzs?\\b",
    "Other": "\\bothers?\\b"
  },
  "sleeve-length-type": {
    "3/4": "\\b34s?\\b",
    "Cap": "\\bcaps?\\b",
    "Long": "\\blongs?\\b",
    "Short": "\\bshorts?\\b",
    "Sleeveless": "\\bsleevelesss?\\b",
    "Spaghetti strap": "\\bspaghetti[\\s\\-]?straps?\\b",
    "Strapless": "\\bstraplesss?\\b",
    "Other": "\\bothers?\\b"
  },
  "cup-size": {
    "A": "\\bas?\\b",
    "AA": "\\baas?\\b",
    "B": "\\bbs?\\b",
    "C": "\\bcs?\\b",
    "D": "\\bds?\\b",
    "DD": "\\bdds?\\b",
    "DDD": "\\bddds?\\b",
    "E": "\\bes?\\b",
    "F": "\\bfs?\\b",
    "FF": "\\bffs?\\b",
    "G": "\\bgs?\\b",
    "GG": "\\bggs?\\b",
    "H": "\\bhs?\\b",
    "HH": "\\bhhs?\\b",
    "I": "\\bis?\\b",
    "J": "\\bjs?\\b",
    "JJ": "\\bjjs?\\b",
    "K": "\\bks?\\b",
    "L": "\\bls?\\b",
    "M": "\\bms?\\b",
    "N": "\\bns?\\b",
    "Other": "\\bothers?\\b"
  },
  "dress-style": {
    "A-line": "\\balines?\\b",
    "Babydoll": "\\bbabydolls?\\b",
    "Blouson": "\\bblousons?\\b",
    "Caftan": "\\bcaftans?\\b",
    "Drop waist": "\\bdrop[\\s\\-]?waists?\\b",
    "Empire waist": "\\bempire[\\s\\-]?waists?\\b",
    "Flared": "\\bflareds?\\b",
    "Gown": "\\bgowns?\\b",
    "Jacket": "\\bjackets?\\b",
    "Mermaid": "\\bmermaids?\\b",
    "Pencil": "\\bpencils?\\b",
    "Peplum": "\\bpeplums?\\b",
    "Sheath": "\\bsheaths?\\b",
    "Shift": "\\bshifts?\\b",
    "Shirt": "\\bshirts?\\b",
    "Skater": "\\bskaters?\\b",
    "Slip": "\\bslips?\\b",
    "Sweater": "\\bsweaters?\\b",
    "Tank": "\\btanks?\\b",
    "Trumpet": "\\btrumpets?\\b",
    "Wrap": "\\bwraps?\\b",
    "Other": "\\bothers?\\b"
  },
  "connectivity-technology": {
    "ANT": "\\bants?\\b",
    "ANT+": "\\bants?\\b",
    "AirPlay": "\\bairplays?\\b",
    "Bluetooth": "\\bbluetooths?\\b",
    "Cellular": "\\bcellulars?\\b",
    "DECT": "\\bdects?\\b",
    "DVI": "\\bdvis?\\b",
    "Ethernet": "\\bethernets?\\b",
    "GPS": "\\bgpss?\\b",
    "HDMI": "\\bhdmis?\\b",
    "Infrared": "\\binfrareds?\\b",
    "LTE": "\\bltes?\\b",
    "Miracast": "\\bmiracasts?\\b",
    "NFC": "\\bnfcs?\\b",
    "Radio": "\\bradios?\\b",
    "Satellite": "\\bsatellites?\\b",
    "USB": "\\busbs?\\b",
    "Wi-Fi": "\\bwifis?\\b",
    "Wired": "\\bwireds?\\b",
    "Wireless": "\\bwirelesss?\\b",
    "Wireless dongle": "\\bwireless[\\s\\-]?dongles?\\b",
    "Other": "\\bothers?\\b"
  },
  "pants-length-type": {
    "Above the knee": "\\babove[\\s\\-]?the[\\s\\-]?knees?\\b",
    "Capri": "\\bcapris?\\b",
    "Cropped": "\\bcroppeds?\\b",
    "Footed": "\\bfooteds?\\b",
    "Knee": "\\bknees?\\b",
    "Long": "\\blongs?\\b",
    "Other": "\\bothers?\\b"
  },
  "pattern": {
    "Abstract": "\\babstracts?\\b",
    "Animal": "\\banimals?\\b",
    "Art": "\\barts?\\b",
    "Bead & reel": "\\bbead[\\s\\-]?[\\s\\-]?reels?\\b",
    "Birds": "\\bbirdss?\\b",
    "Brick": "\\bbricks?\\b",
    "Bull's eye": "\\bbulls[\\s\\-]?eyes?\\b",
    "Camouflage": "\\bcamouflages?\\b",
    "Characters": "\\bcharacterss?\\b",
    "Checkered": "\\bcheckereds?\\b",
    "Chevron": "\\bchevrons?\\b",
    "Chinoiserie": "\\bchinoiseries?\\b",
    "Christmas": "\\bchristmass?\\b",
    "Collage": "\\bcollages?\\b",
    "Coral": "\\bcorals?\\b",
    "Damask": "\\bdamasks?\\b",
    "Diagonal": "\\bdiagonals?\\b",
    "Diamond": "\\bdiamonds?\\b",
    "Dog's tooth": "\\bdogs[\\s\\-]?tooths?\\b",
    "Dots": "\\bdotss?\\b",
    "Egg & dart": "\\begg[\\s\\-]?[\\s\\-]?darts?\\b",
    "Ethnic": "\\bethnics?\\b",
    "Everlasting knot": "\\beverlasting[\\s\\-]?knots?\\b",
    "Floral": "\\bflorals?\\b",
    "Fret": "\\bfrets?\\b",
    "Geometric": "\\bgeometrics?\\b",
    "Guilloche": "\\bguilloches?\\b",
    "Hearts": "\\bheartss?\\b",
    "Illusion": "\\billusions?\\b",
    "Lace": "\\blaces?\\b",
    "Leaves": "\\bleavess?\\b",
    "Logo": "\\blogos?\\b",
    "Mosaic": "\\bmosaics?\\b",
    "Ogee": "\\bogees?\\b",
    "Organic": "\\borganics?\\b",
    "Paisley": "\\bpaisleys?\\b",
    "Plaid": "\\bplaids?\\b",
    "Rainbow": "\\brainbows?\\b",
    "Random": "\\brandoms?\\b",
    "Scale": "\\bscales?\\b",
    "Scroll": "\\bscrolls?\\b",
    "Solid": "\\bsolids?\\b",
    "Stars": "\\bstarss?\\b",
    "Striped": "\\bstripeds?\\b",
    "Swirl": "\\bswirls?\\b",
    "Text": "\\btexts?\\b",
    "Texture": "\\btextures?\\b",
    "Tie-dye": "\\btiedyes?\\b",
    "Trellis": "\\btrelliss?\\b",
    "Vehicle": "\\bvehicles?\\b",
    "Other": "\\bothers?\\b"
  },
  "material": {
    "Acrylic": "\\bacrylics?\\b",
    "Aluminum": "\\baluminums?\\b",
    "Angora": "\\bangoras?\\b",
    "Bamboo": "\\bbamboos?\\b",
    "Biodegradable materials": "\\bbiodegradable[\\s\\-]?materialss?\\b",
    "Brass": "\\bbrasss?\\b",
    "Bronze": "\\bbronzes?\\b",
    "Canvas": "\\bcanvass?\\b",
    "Carbon": "\\bcarbons?\\b",
    "Cardboard": "\\bcardboards?\\b",
    "Cashmere": "\\bcashmeres?\\b",
    "Ceramic": "\\bceramics?\\b",
    "Chrome": "\\bchromes?\\b",
    "Clay": "\\bclays?\\b",
    "Coir": "\\bcoirs?\\b",
    "Concrete": "\\bconcretes?\\b",
    "Copper": "\\bcoppers?\\b",
    "Corduroy": "\\bcorduroys?\\b",
    "Cork": "\\bcorks?\\b",
    "Cotton": "\\bcottons?\\b",
    "Denim": "\\bdenims?\\b",
    "Fabric": "\\bfabrics?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Felt": "\\bfelts?\\b",
    "Fiberglass": "\\bfiberglasss?\\b",
    "Flannel": "\\bflannels?\\b",
    "Fleece": "\\bfleeces?\\b",
    "Fur": "\\bfurs?\\b",
    "Glass": "\\bglasss?\\b",
    "Graphite": "\\bgraphites?\\b",
    "Hemp": "\\bhemps?\\b",
    "Iron": "\\birons?\\b",
    "Jute": "\\bjutes?\\b",
    "Latex": "\\blatexs?\\b",
    "Leather": "\\bleathers?\\b",
    "Linen": "\\blinens?\\b",
    "Lycra": "\\blycras?\\b",
    "Lyocell": "\\blyocells?\\b",
    "Marble": "\\bmarbles?\\b",
    "Medium density fiberboard (MDF)": "\\bmedium[\\s\\-]?density[\\s\\-]?fiberboard[\\s\\-]?mdfs?\\b",
    "Merino": "\\bmerinos?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Metal": "\\bmetals?\\b",
    "Modal": "\\bmodals?\\b",
    "Mohair": "\\bmohairs?\\b",
    "Neoprene": "\\bneoprenes?\\b",
    "Nylon": "\\bnylons?\\b",
    "Paper": "\\bpapers?\\b",
    "Plastic": "\\bplastics?\\b",
    "Plush": "\\bplushs?\\b",
    "Plywood": "\\bplywoods?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polyethylene (PE)": "\\bpolyethylene[\\s\\-]?pes?\\b",
    "Polypropylene (PP)": "\\bpolypropylene[\\s\\-]?pps?\\b",
    "Polyurethane (PU)": "\\bpolyurethane[\\s\\-]?pus?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Porcelain": "\\bporcelains?\\b",
    "Rattan": "\\brattans?\\b",
    "Rayon": "\\brayons?\\b",
    "Resin": "\\bresins?\\b",
    "Rubber": "\\brubbers?\\b",
    "Satin": "\\bsatins?\\b",
    "Sherpa": "\\bsherpas?\\b",
    "Silicone": "\\bsilicones?\\b",
    "Silk": "\\bsilks?\\b",
    "Stainless steel": "\\bstainless[\\s\\-]?steels?\\b",
    "Stone": "\\bstones?\\b",
    "Suede": "\\bsuedes?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Terrycloth": "\\bterrycloths?\\b",
    "Thermoplastic elastomer (TPE)": "\\bthermoplastic[\\s\\-]?elastomer[\\s\\-]?tpes?\\b",
    "Thermoplastic polyurethane (TPU)": "\\bthermoplastic[\\s\\-]?polyurethane[\\s\\-]?tpus?\\b",
    "Tweed": "\\btweeds?\\b",
    "Twill": "\\btwills?\\b",
    "Velour": "\\bvelours?\\b",
    "Velvet": "\\bvelvets?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "Viscose": "\\bviscoses?\\b",
    "Wood": "\\bwoods?\\b",
    "Wool": "\\bwools?\\b",
    "Other": "\\bothers?\\b"
  },
  "decoration-material": {
    "Acrylic": "\\bacrylics?\\b",
    "Aluminum": "\\baluminums?\\b",
    "Bamboo": "\\bbamboos?\\b",
    "Brass": "\\bbrasss?\\b",
    "Bronze": "\\bbronzes?\\b",
    "Canvas": "\\bcanvass?\\b",
    "Capiz": "\\bcapizs?\\b",
    "Cardboard": "\\bcardboards?\\b",
    "Cast iron": "\\bcast[\\s\\-]?irons?\\b",
    "Ceramic": "\\bceramics?\\b",
    "Chrome": "\\bchromes?\\b",
    "Concrete": "\\bconcretes?\\b",
    "Copper": "\\bcoppers?\\b",
    "Cork": "\\bcorks?\\b",
    "Cotton": "\\bcottons?\\b",
    "Crystal": "\\bcrystals?\\b",
    "Fabric": "\\bfabrics?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Feathers": "\\bfeatherss?\\b",
    "Felt": "\\bfelts?\\b",
    "Glass": "\\bglasss?\\b",
    "Hemp": "\\bhemps?\\b",
    "Iron": "\\birons?\\b",
    "Jute": "\\bjutes?\\b",
    "Latex": "\\blatexs?\\b",
    "Leather": "\\bleathers?\\b",
    "Marble": "\\bmarbles?\\b",
    "Medium density fiberboard (MDF)": "\\bmedium[\\s\\-]?density[\\s\\-]?fiberboard[\\s\\-]?mdfs?\\b",
    "Melamine": "\\bmelamines?\\b",
    "Metal": "\\bmetals?\\b",
    "Nylon": "\\bnylons?\\b",
    "Paper": "\\bpapers?\\b",
    "Papier-m\u00e2ch\u00e9": "\\bpapiermchs?\\b",
    "Plastic": "\\bplastics?\\b",
    "Plush": "\\bplushs?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polypropylene (PP)": "\\bpolypropylene[\\s\\-]?pps?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Porcelain": "\\bporcelains?\\b",
    "Rattan": "\\brattans?\\b",
    "Resin": "\\bresins?\\b",
    "Rubber": "\\brubbers?\\b",
    "Satin": "\\bsatins?\\b",
    "Sequins": "\\bsequinss?\\b",
    "Silicone": "\\bsilicones?\\b",
    "Silk": "\\bsilks?\\b",
    "Stainless steel": "\\bstainless[\\s\\-]?steels?\\b",
    "Steel": "\\bsteels?\\b",
    "Stone": "\\bstones?\\b",
    "Suede": "\\bsuedes?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Terracotta": "\\bterracottas?\\b",
    "Velour": "\\bvelours?\\b",
    "Velvet": "\\bvelvets?\\b",
    "Veneer": "\\bveneers?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "Wax": "\\bwaxs?\\b",
    "Wood": "\\bwoods?\\b",
    "Wool": "\\bwools?\\b",
    "Zinc": "\\bzincs?\\b",
    "Other": "\\bothers?\\b"
  },
  "fabric": {
    "Acrylic": "\\bacrylics?\\b",
    "Angora": "\\bangoras?\\b",
    "Bamboo": "\\bbamboos?\\b",
    "Canvas": "\\bcanvass?\\b",
    "Cashmere": "\\bcashmeres?\\b",
    "Corduroy": "\\bcorduroys?\\b",
    "Cork": "\\bcorks?\\b",
    "Cotton": "\\bcottons?\\b",
    "Denim": "\\bdenims?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Felt": "\\bfelts?\\b",
    "Flannel": "\\bflannels?\\b",
    "Fleece": "\\bfleeces?\\b",
    "Fur": "\\bfurs?\\b",
    "Hemp": "\\bhemps?\\b",
    "Jute": "\\bjutes?\\b",
    "Latex": "\\blatexs?\\b",
    "Leather": "\\bleathers?\\b",
    "Linen": "\\blinens?\\b",
    "Lycra": "\\blycras?\\b",
    "Lyocell": "\\blyocells?\\b",
    "Merino": "\\bmerinos?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Modal": "\\bmodals?\\b",
    "Mohair": "\\bmohairs?\\b",
    "Neoprene": "\\bneoprenes?\\b",
    "Nylon": "\\bnylons?\\b",
    "Plastic": "\\bplastics?\\b",
    "Plush": "\\bplushs?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Rattan": "\\brattans?\\b",
    "Rayon": "\\brayons?\\b",
    "Rubber": "\\brubbers?\\b",
    "Satin": "\\bsatins?\\b",
    "Sherpa": "\\bsherpas?\\b",
    "Silk": "\\bsilks?\\b",
    "Suede": "\\bsuedes?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Terrycloth": "\\bterrycloths?\\b",
    "Tweed": "\\btweeds?\\b",
    "Twill": "\\btwills?\\b",
    "Velour": "\\bvelours?\\b",
    "Velvet": "\\bvelvets?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "Viscose": "\\bviscoses?\\b",
    "Wool": "\\bwools?\\b",
    "Other": "\\bothers?\\b"
  },
  "handwear-material": {
    "Acrylic": "\\bacrylics?\\b",
    "Bamboo": "\\bbamboos?\\b",
    "Cotton": "\\bcottons?\\b",
    "Elastomer": "\\belastomers?\\b",
    "Ethylene vinyl acetate (EVA)": "\\bethylene[\\s\\-]?vinyl[\\s\\-]?acetate[\\s\\-]?evas?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Fleece": "\\bfleeces?\\b",
    "Kevlar": "\\bkevlars?\\b",
    "Latex": "\\blatexs?\\b",
    "Leather": "\\bleathers?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Microfiber": "\\bmicrofibers?\\b",
    "Neoprene": "\\bneoprenes?\\b",
    "Nitrile": "\\bnitriles?\\b",
    "Nylon": "\\bnylons?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polyethylene (PE)": "\\bpolyethylene[\\s\\-]?pes?\\b",
    "Polyurethane (PU)": "\\bpolyurethane[\\s\\-]?pus?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Satin": "\\bsatins?\\b",
    "Silk": "\\bsilks?\\b",
    "Spandex": "\\bspandexs?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Wool": "\\bwools?\\b",
    "Other": "\\bothers?\\b"
  },
  "jewelry-material": {
    "Acrylic": "\\bacrylics?\\b",
    "Alcantara": "\\balcantaras?\\b",
    "Aluminum": "\\baluminums?\\b",
    "Bakelite": "\\bbakelites?\\b",
    "Bamboo": "\\bbamboos?\\b",
    "Black rhodium-plated": "\\bblack[\\s\\-]?rhodiumplateds?\\b",
    "Brass": "\\bbrasss?\\b",
    "Bronze": "\\bbronzes?\\b",
    "Bronze-plated": "\\bbronzeplateds?\\b",
    "Carbon fiber": "\\bcarbon[\\s\\-]?fibers?\\b",
    "Ceramic": "\\bceramics?\\b",
    "Chrome": "\\bchromes?\\b",
    "Copper": "\\bcoppers?\\b",
    "Copper-plated": "\\bcopperplateds?\\b",
    "Cordura": "\\bcorduras?\\b",
    "Cork": "\\bcorks?\\b",
    "Cotton": "\\bcottons?\\b",
    "Diamond": "\\bdiamonds?\\b",
    "Duralumin": "\\bduralumins?\\b",
    "Enamel": "\\benamels?\\b",
    "Fabric": "\\bfabrics?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Felt": "\\bfelts?\\b",
    "Fiberglass": "\\bfiberglasss?\\b",
    "Fur": "\\bfurs?\\b",
    "Glass": "\\bglasss?\\b",
    "Gold": "\\bgolds?\\b",
    "Gold-plated": "\\bgoldplateds?\\b",
    "Hemp": "\\bhemps?\\b",
    "Iron": "\\birons?\\b",
    "Jute": "\\bjutes?\\b",
    "Latex": "\\blatexs?\\b",
    "Leather": "\\bleathers?\\b",
    "Linen": "\\blinens?\\b",
    "Marble": "\\bmarbles?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Metal": "\\bmetals?\\b",
    "Microfiber": "\\bmicrofibers?\\b",
    "Nickel": "\\bnickels?\\b",
    "Nickel-plated": "\\bnickelplateds?\\b",
    "Nylon": "\\bnylons?\\b",
    "Palladium": "\\bpalladiums?\\b",
    "Palladium-plated": "\\bpalladiumplateds?\\b",
    "Plastic": "\\bplastics?\\b",
    "Platinum": "\\bplatinums?\\b",
    "Platinum-plated": "\\bplatinumplateds?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Porcelain": "\\bporcelains?\\b",
    "Precious resin": "\\bprecious[\\s\\-]?resins?\\b",
    "Red gold": "\\bred[\\s\\-]?golds?\\b",
    "Resin": "\\bresins?\\b",
    "Rhodium-plated": "\\brhodiumplateds?\\b",
    "Rose gold": "\\brose[\\s\\-]?golds?\\b",
    "Rose gold-plated": "\\brose[\\s\\-]?goldplateds?\\b",
    "Rubber": "\\brubbers?\\b",
    "Satin": "\\bsatins?\\b",
    "Silk": "\\bsilks?\\b",
    "Silver": "\\bsilvers?\\b",
    "Silver-plated": "\\bsilverplateds?\\b",
    "Stainless steel": "\\bstainless[\\s\\-]?steels?\\b",
    "Sterling silver": "\\bsterling[\\s\\-]?silvers?\\b",
    "Suede": "\\bsuedes?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Tin-plated": "\\btinplateds?\\b",
    "Titanium": "\\btitaniums?\\b",
    "Velvet": "\\bvelvets?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "White gold": "\\bwhite[\\s\\-]?golds?\\b",
    "White gold-plated": "\\bwhite[\\s\\-]?goldplateds?\\b",
    "Wood": "\\bwoods?\\b",
    "Wool": "\\bwools?\\b",
    "Other": "\\bothers?\\b"
  },
  "bag-case-material": {
    "Acrylic": "\\bacrylics?\\b",
    "Alcantara": "\\balcantaras?\\b",
    "Aluminum": "\\baluminums?\\b",
    "Burlap": "\\bburlaps?\\b",
    "Canvas": "\\bcanvass?\\b",
    "Carbon fiber": "\\bcarbon[\\s\\-]?fibers?\\b",
    "Cordura": "\\bcorduras?\\b",
    "Cotton": "\\bcottons?\\b",
    "Denim": "\\bdenims?\\b",
    "Ethylene vinyl acetate (EVA)": "\\bethylene[\\s\\-]?vinyl[\\s\\-]?acetate[\\s\\-]?evas?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Felt": "\\bfelts?\\b",
    "Fiberglass": "\\bfiberglasss?\\b",
    "Leather": "\\bleathers?\\b",
    "Leatherette": "\\bleatherettes?\\b",
    "Linen": "\\blinens?\\b",
    "Memory foam": "\\bmemory[\\s\\-]?foams?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Metal": "\\bmetals?\\b",
    "Microfiber": "\\bmicrofibers?\\b",
    "Neoprene": "\\bneoprenes?\\b",
    "Nylon": "\\bnylons?\\b",
    "Plastic": "\\bplastics?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Ripstop": "\\bripstops?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Thermoplastic polyurethane (TPU)": "\\bthermoplastic[\\s\\-]?polyurethane[\\s\\-]?tpus?\\b",
    "Tweed": "\\btweeds?\\b",
    "Velvet": "\\bvelvets?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "Wood": "\\bwoods?\\b",
    "Other": "\\bothers?\\b"
  },
  "bra-style": {
    "Adhesive": "\\badhesives?\\b",
    "Balconette": "\\bbalconettes?\\b",
    "Bandeau": "\\bbandeaus?\\b",
    "Bralette": "\\bbralettes?\\b",
    "Bullet": "\\bbullets?\\b",
    "Contour": "\\bcontours?\\b",
    "Convertible": "\\bconvertibles?\\b",
    "Halter": "\\bhalters?\\b",
    "Longline": "\\blonglines?\\b",
    "Minimizer": "\\bminimizers?\\b",
    "Molded": "\\bmoldeds?\\b",
    "Plunge": "\\bplunges?\\b",
    "Push-up": "\\bpushups?\\b",
    "Racerback": "\\bracerbacks?\\b",
    "Strapless": "\\bstraplesss?\\b",
    "T-shirt": "\\btshirts?\\b",
    "Triangle": "\\btriangles?\\b",
    "Underwire": "\\bunderwires?\\b",
    "Wireless": "\\bwirelesss?\\b",
    "Other": "\\bothers?\\b"
  },
  "bra-strap-type": {
    "Adjustable": "\\badjustables?\\b",
    "Convertible": "\\bconvertibles?\\b",
    "Cross-back": "\\bcrossbacks?\\b",
    "Racerback": "\\bracerbacks?\\b",
    "Standard": "\\bstandards?\\b",
    "Other": "\\bothers?\\b"
  },
  "bra-features": {
    "Adjustable band": "\\badjustable[\\s\\-]?bands?\\b",
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Convertible strap": "\\bconvertible[\\s\\-]?straps?\\b",
    "Removable padding": "\\bremovable[\\s\\-]?paddings?\\b",
    "Seamless": "\\bseamlesss?\\b",
    "Sweat-wicking fabric": "\\bsweatwicking[\\s\\-]?fabrics?\\b",
    "Underwire support": "\\bunderwire[\\s\\-]?supports?\\b",
    "Other": "\\bothers?\\b"
  },
  "handwear-features": {
    "Adjustable closure": "\\badjustable[\\s\\-]?closures?\\b",
    "Enhanced grip": "\\benhanced[\\s\\-]?grips?\\b",
    "Insulating properties": "\\binsulating[\\s\\-]?propertiess?\\b",
    "Touchscreen compatible": "\\btouchscreen[\\s\\-]?compatibles?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "Other": "\\bothers?\\b"
  },
  "bag-case-storage-features": {
    "Adjustable dividers": "\\badjustable[\\s\\-]?dividerss?\\b",
    "Bow holders": "\\bbow[\\s\\-]?holderss?\\b",
    "Built-in compartments": "\\bbuiltin[\\s\\-]?compartmentss?\\b",
    "Clear window": "\\bclear[\\s\\-]?windows?\\b",
    "Elastic loops": "\\belastic[\\s\\-]?loopss?\\b",
    "External pockets": "\\bexternal[\\s\\-]?pocketss?\\b",
    "Garment mesh": "\\bgarment[\\s\\-]?meshs?\\b",
    "Hanging toiletry": "\\bhanging[\\s\\-]?toiletrys?\\b",
    "Hidden pockets": "\\bhidden[\\s\\-]?pocketss?\\b",
    "Insulated bottle pocket": "\\binsulated[\\s\\-]?bottle[\\s\\-]?pockets?\\b",
    "Keychain holder": "\\bkeychain[\\s\\-]?holders?\\b",
    "Laptop compartment": "\\blaptop[\\s\\-]?compartments?\\b",
    "Mallet holders": "\\bmallet[\\s\\-]?holderss?\\b",
    "Protective sleeves": "\\bprotective[\\s\\-]?sleevess?\\b",
    "Removable pouch": "\\bremovable[\\s\\-]?pouchs?\\b",
    "Sheet music pocket": "\\bsheet[\\s\\-]?music[\\s\\-]?pockets?\\b",
    "Single compartment": "\\bsingle[\\s\\-]?compartments?\\b",
    "Water bottle holder": "\\bwater[\\s\\-]?bottle[\\s\\-]?holders?\\b"
  },
  "headwear-features": {
    "Adjustable fit": "\\badjustable[\\s\\-]?fits?\\b",
    "Collapsible": "\\bcollapsibles?\\b",
    "UV protection": "\\buv[\\s\\-]?protections?\\b",
    "Versatile": "\\bversatiles?\\b",
    "Other": "\\bothers?\\b"
  },
  "bag-case-features": {
    "Adjustable size": "\\badjustable[\\s\\-]?sizes?\\b",
    "Anti-theft": "\\bantithefts?\\b",
    "Convertible": "\\bconvertibles?\\b",
    "Dustproof": "\\bdustproofs?\\b",
    "Easy to install": "\\beasy[\\s\\-]?to[\\s\\-]?installs?\\b",
    "Fire resistant": "\\bfire[\\s\\-]?resistants?\\b",
    "Four-wheel spinner": "\\bfourwheel[\\s\\-]?spinners?\\b",
    "Internal padding": "\\binternal[\\s\\-]?paddings?\\b",
    "Lightweight": "\\blightweights?\\b",
    "Lockable": "\\blockables?\\b",
    "Luggage tag": "\\bluggage[\\s\\-]?tags?\\b",
    "RFID protection": "\\brfid[\\s\\-]?protections?\\b",
    "Reflective": "\\breflectives?\\b",
    "Shockproof": "\\bshockproofs?\\b",
    "TSA approved": "\\btsa[\\s\\-]?approveds?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "Wheeled": "\\bwheeleds?\\b"
  },
  "swimwear-features": {
    "Adjustable strap": "\\badjustable[\\s\\-]?straps?\\b",
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Chlorine resistant": "\\bchlorine[\\s\\-]?resistants?\\b",
    "Elastic waistband": "\\belastic[\\s\\-]?waistbands?\\b",
    "Flattering silhouette": "\\bflattering[\\s\\-]?silhouettes?\\b",
    "Lightweight": "\\blightweights?\\b",
    "Quick drying": "\\bquick[\\s\\-]?dryings?\\b",
    "UPF sun protection": "\\bupf[\\s\\-]?sun[\\s\\-]?protections?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Other": "\\bothers?\\b"
  },
  "maternity-clothing-features": {
    "Adjustable strap": "\\badjustable[\\s\\-]?straps?\\b",
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Chlorine resistant": "\\bchlorine[\\s\\-]?resistants?\\b",
    "Elastic waistband": "\\belastic[\\s\\-]?waistbands?\\b",
    "Flattering silhouette": "\\bflattering[\\s\\-]?silhouettes?\\b",
    "Flexible": "\\bflexibles?\\b",
    "Lightweight": "\\blightweights?\\b",
    "Quick drying": "\\bquick[\\s\\-]?dryings?\\b",
    "Room for belly growth": "\\broom[\\s\\-]?for[\\s\\-]?belly[\\s\\-]?growths?\\b",
    "Supportive cups": "\\bsupportive[\\s\\-]?cupss?\\b",
    "UPF sun protection": "\\bupf[\\s\\-]?sun[\\s\\-]?protections?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Other": "\\bothers?\\b"
  },
  "closure-type": {
    "Adjustable straps": "\\badjustable[\\s\\-]?strapss?\\b",
    "Adjustable/Pull": "\\badjustablepulls?\\b",
    "Buckles": "\\bbuckless?\\b",
    "Buttons": "\\bbuttonss?\\b",
    "Clasp": "\\bclasps?\\b",
    "Clip-on": "\\bclipons?\\b",
    "Drawstring": "\\bdrawstrings?\\b",
    "Elastic": "\\belastics?\\b",
    "Hook & eye": "\\bhook[\\s\\-]?[\\s\\-]?eyes?\\b",
    "Hook & loop": "\\bhook[\\s\\-]?[\\s\\-]?loops?\\b",
    "Lace-up": "\\blaceups?\\b",
    "Magnetic": "\\bmagnetics?\\b",
    "None": "\\bnones?\\b",
    "Screw-on": "\\bscrewons?\\b",
    "Slip-on": "\\bslipons?\\b",
    "Snap": "\\bsnaps?\\b",
    "Straps": "\\bstrapss?\\b",
    "Ties": "\\btiess?\\b",
    "Toggle": "\\btoggles?\\b",
    "Velcro": "\\bvelcros?\\b",
    "Zipper": "\\bzippers?\\b",
    "Other": "\\bothers?\\b"
  },
  "activewear-clothing-features": {
    "Adjustable waistband": "\\badjustable[\\s\\-]?waistbands?\\b",
    "Anti-chafing design": "\\bantichafing[\\s\\-]?designs?\\b",
    "Anti-static properties": "\\bantistatic[\\s\\-]?propertiess?\\b",
    "Body contouring fit": "\\bbody[\\s\\-]?contouring[\\s\\-]?fits?\\b",
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Compression": "\\bcompressions?\\b",
    "Flatlock seams": "\\bflatlock[\\s\\-]?seamss?\\b",
    "Four-way stretch": "\\bfourway[\\s\\-]?stretchs?\\b",
    "Hidden pockets": "\\bhidden[\\s\\-]?pocketss?\\b",
    "High-visibility accents": "\\bhighvisibility[\\s\\-]?accentss?\\b",
    "Mesh panels": "\\bmesh[\\s\\-]?panelss?\\b",
    "Moisture wicking": "\\bmoisture[\\s\\-]?wickings?\\b",
    "Odor resistant": "\\bodor[\\s\\-]?resistants?\\b",
    "Quick drying": "\\bquick[\\s\\-]?dryings?\\b",
    "Reflective": "\\breflectives?\\b",
    "Removable padding": "\\bremovable[\\s\\-]?paddings?\\b",
    "Seamless": "\\bseamlesss?\\b",
    "Sweatproof pockets": "\\bsweatproof[\\s\\-]?pocketss?\\b",
    "Temperature regulation": "\\btemperature[\\s\\-]?regulations?\\b",
    "Thumbholes": "\\bthumbholess?\\b",
    "UV protection": "\\buv[\\s\\-]?protections?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Ventilation": "\\bventilations?\\b",
    "Waterproof coating": "\\bwaterproof[\\s\\-]?coatings?\\b",
    "Other": "\\bothers?\\b"
  },
  "baby-toddler-clothing-features": {
    "Adjustable waistband": "\\badjustable[\\s\\-]?waistbands?\\b",
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Easy-to-use buttons/snaps": "\\beasytouse[\\s\\-]?buttonssnapss?\\b",
    "Hypoallergenic": "\\bhypoallergenics?\\b",
    "Quick drying": "\\bquick[\\s\\-]?dryings?\\b",
    "Safety buttons": "\\bsafety[\\s\\-]?buttonss?\\b",
    "Tagless": "\\btaglesss?\\b",
    "UV protection": "\\buv[\\s\\-]?protections?\\b"
  },
  "activity": {
    "Aerobics": "\\baerobicss?\\b",
    "Aikido": "\\baikidos?\\b",
    "Air hockey": "\\bair[\\s\\-]?hockeys?\\b",
    "Australian football": "\\baustralian[\\s\\-]?footballs?\\b",
    "Badminton": "\\bbadmintons?\\b",
    "Ballet": "\\bballets?\\b",
    "Baseball": "\\bbaseballs?\\b",
    "Basketball": "\\bbasketballs?\\b",
    "Boxing": "\\bboxings?\\b",
    "Brazilian jiu-jitsu": "\\bbrazilian[\\s\\-]?jiujitsus?\\b",
    "Car racing": "\\bcar[\\s\\-]?racings?\\b",
    "Cheerleading": "\\bcheerleadings?\\b",
    "Climbing": "\\bclimbings?\\b",
    "Cricket": "\\bcrickets?\\b",
    "Cycling": "\\bcyclings?\\b",
    "Dancing": "\\bdancings?\\b",
    "Darts": "\\bdartss?\\b",
    "Field hockey": "\\bfield[\\s\\-]?hockeys?\\b",
    "Fishing": "\\bfishings?\\b",
    "Floorball": "\\bfloorballs?\\b",
    "Football": "\\bfootballs?\\b",
    "Futsal": "\\bfutsals?\\b",
    "Gaelic football": "\\bgaelic[\\s\\-]?footballs?\\b",
    "Golf": "\\bgolfs?\\b",
    "Gymnastics": "\\bgymnasticss?\\b",
    "Handball": "\\bhandballs?\\b",
    "Hiking": "\\bhikings?\\b",
    "Hockey": "\\bhockeys?\\b",
    "Horse riding": "\\bhorse[\\s\\-]?ridings?\\b",
    "Hunting": "\\bhuntings?\\b",
    "Hurling": "\\bhurlings?\\b",
    "Ice hockey": "\\bice[\\s\\-]?hockeys?\\b",
    "Inline skating": "\\binline[\\s\\-]?skatings?\\b",
    "Judo": "\\bjudos?\\b",
    "Karate": "\\bkarates?\\b",
    "Kickboxing": "\\bkickboxings?\\b",
    "Krav maga": "\\bkrav[\\s\\-]?magas?\\b",
    "Lacrosse": "\\blacrosses?\\b",
    "Mixed martial arts (MMA)": "\\bmixed[\\s\\-]?martial[\\s\\-]?arts[\\s\\-]?mmas?\\b",
    "Motorcycling": "\\bmotorcyclings?\\b",
    "Muay thai": "\\bmuay[\\s\\-]?thais?\\b",
    "Netball": "\\bnetballs?\\b",
    "Padel": "\\bpadels?\\b",
    "Pilates": "\\bpilatess?\\b",
    "Racquetball": "\\bracquetballs?\\b",
    "Rounders": "\\brounderss?\\b",
    "Rugby": "\\brugbys?\\b",
    "Running": "\\brunnings?\\b",
    "Skateboarding": "\\bskateboardings?\\b",
    "Skiing": "\\bskiings?\\b",
    "Snowboarding": "\\bsnowboardings?\\b",
    "Soccer": "\\bsoccers?\\b",
    "Softball": "\\bsoftballs?\\b",
    "Squash": "\\bsquashs?\\b",
    "Taekwondo": "\\btaekwondos?\\b",
    "Team handball": "\\bteam[\\s\\-]?handballs?\\b",
    "Tennis": "\\btenniss?\\b",
    "Track & field": "\\btrack[\\s\\-]?[\\s\\-]?fields?\\b",
    "Ultimate frisbee": "\\bultimate[\\s\\-]?frisbees?\\b",
    "Universal": "\\buniversals?\\b",
    "Volleyball": "\\bvolleyballs?\\b",
    "Water polo": "\\bwater[\\s\\-]?polos?\\b",
    "Wrestling": "\\bwrestlings?\\b",
    "Yoga": "\\byogas?\\b",
    "Other": "\\bothers?\\b"
  },
  "smart-watch-features": {
    "Alarm": "\\balarms?\\b",
    "Anti-reflective": "\\bantireflectives?\\b",
    "Blood oxygen level monitoring": "\\bblood[\\s\\-]?oxygen[\\s\\-]?level[\\s\\-]?monitorings?\\b",
    "Blood pressure monitoring": "\\bblood[\\s\\-]?pressure[\\s\\-]?monitorings?\\b",
    "Camera control": "\\bcamera[\\s\\-]?controls?\\b",
    "Compass": "\\bcompasss?\\b",
    "Customizable watch faces": "\\bcustomizable[\\s\\-]?watch[\\s\\-]?facess?\\b",
    "Device location feature": "\\bdevice[\\s\\-]?location[\\s\\-]?features?\\b",
    "ECG monitoring": "\\becg[\\s\\-]?monitorings?\\b",
    "Fitness tracker": "\\bfitness[\\s\\-]?trackers?\\b",
    "GPS support": "\\bgps[\\s\\-]?supports?\\b",
    "Heart rate monitor": "\\bheart[\\s\\-]?rate[\\s\\-]?monitors?\\b",
    "Interchangeable strap": "\\binterchangeable[\\s\\-]?straps?\\b",
    "Music control": "\\bmusic[\\s\\-]?controls?\\b",
    "Offline music storage": "\\boffline[\\s\\-]?music[\\s\\-]?storages?\\b",
    "Sleep tracker": "\\bsleep[\\s\\-]?trackers?\\b",
    "Step counter": "\\bstep[\\s\\-]?counters?\\b",
    "Thermometer": "\\bthermometers?\\b",
    "Touchscreen": "\\btouchscreens?\\b",
    "Vibration": "\\bvibrations?\\b",
    "Voice control": "\\bvoice[\\s\\-]?controls?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "World timer": "\\bworld[\\s\\-]?timers?\\b",
    "Other": "\\bothers?\\b"
  },
  "watch-features": {
    "Alarm": "\\balarms?\\b",
    "Anti-reflective": "\\bantireflectives?\\b",
    "Automatic movement": "\\bautomatic[\\s\\-]?movements?\\b",
    "Date display": "\\bdate[\\s\\-]?displays?\\b",
    "Deployment clasp": "\\bdeployment[\\s\\-]?clasps?\\b",
    "Interchangeable strap": "\\binterchangeable[\\s\\-]?straps?\\b",
    "Limited edition": "\\blimited[\\s\\-]?editions?\\b",
    "Luminous hands": "\\bluminous[\\s\\-]?handss?\\b",
    "Luminous markers": "\\bluminous[\\s\\-]?markerss?\\b",
    "Magnetic resistance": "\\bmagnetic[\\s\\-]?resistances?\\b",
    "Manual winding": "\\bmanual[\\s\\-]?windings?\\b",
    "Moon phase display": "\\bmoon[\\s\\-]?phase[\\s\\-]?displays?\\b",
    "Multiple time zones": "\\bmultiple[\\s\\-]?time[\\s\\-]?zoness?\\b",
    "Perpetual calendar": "\\bperpetual[\\s\\-]?calendars?\\b",
    "Power reserve indicator": "\\bpower[\\s\\-]?reserve[\\s\\-]?indicators?\\b",
    "Quartz movement": "\\bquartz[\\s\\-]?movements?\\b",
    "Rotating bezel": "\\brotating[\\s\\-]?bezels?\\b",
    "Screw-down crown": "\\bscrewdown[\\s\\-]?crowns?\\b",
    "Shockproof": "\\bshockproofs?\\b",
    "Skeleton dial": "\\bskeleton[\\s\\-]?dials?\\b",
    "Solar powered": "\\bsolar[\\s\\-]?powereds?\\b",
    "Tachymeter": "\\btachymeters?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "World timer": "\\bworld[\\s\\-]?timers?\\b",
    "Other": "\\bothers?\\b"
  },
  "watch-band-material": {
    "Alcantara": "\\balcantaras?\\b",
    "Canvas": "\\bcanvass?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Leather": "\\bleathers?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Metal": "\\bmetals?\\b",
    "Microfiber": "\\bmicrofibers?\\b",
    "Nylon": "\\bnylons?\\b",
    "Plastic": "\\bplastics?\\b",
    "Polyamide (PA)": "\\bpolyamide[\\s\\-]?pas?\\b",
    "Polycarbonate (PC)": "\\bpolycarbonate[\\s\\-]?pcs?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polyurethane (PU)": "\\bpolyurethane[\\s\\-]?pus?\\b",
    "Rubber": "\\brubbers?\\b",
    "Silicone": "\\bsilicones?\\b",
    "Stainless steel": "\\bstainless[\\s\\-]?steels?\\b",
    "Thermoplastic elastomer (TPE)": "\\bthermoplastic[\\s\\-]?elastomer[\\s\\-]?tpes?\\b",
    "Thermoplastic polyurethane (TPU)": "\\bthermoplastic[\\s\\-]?polyurethane[\\s\\-]?tpus?\\b",
    "Titanium": "\\btitaniums?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "Other": "\\bothers?\\b"
  },
  "costume-theme": {
    "Aliens": "\\balienss?\\b",
    "Angels/Demons": "\\bangelsdemonss?\\b",
    "Animals": "\\banimalss?\\b",
    "Carnival/Mardi Gras": "\\bcarnivalmardi[\\s\\-]?grass?\\b",
    "Cartoon/Animated characters": "\\bcartoonanimated[\\s\\-]?characterss?\\b",
    "Celebrities": "\\bcelebritiess?\\b",
    "Contemporary": "\\bcontemporarys?\\b",
    "Cultural": "\\bculturals?\\b",
    "Fairy tales": "\\bfairy[\\s\\-]?taless?\\b",
    "Fantasy": "\\bfantasys?\\b",
    "Ghosts": "\\bghostss?\\b",
    "Heroes": "\\bheroess?\\b",
    "Historical": "\\bhistoricals?\\b",
    "Horror": "\\bhorrors?\\b",
    "Movie/TV characters": "\\bmovietv[\\s\\-]?characterss?\\b",
    "Mythological": "\\bmythologicals?\\b",
    "Occupations": "\\boccupationss?\\b",
    "Pirates": "\\bpiratess?\\b",
    "Princesses": "\\bprincessess?\\b",
    "Retro/Vintage": "\\bretrovintages?\\b",
    "Robots": "\\brobotss?\\b",
    "Sci-fi": "\\bscifis?\\b",
    "Sports": "\\bsportss?\\b",
    "Superheroes": "\\bsuperheroess?\\b",
    "Vampires": "\\bvampiress?\\b",
    "Villains": "\\bvillainss?\\b",
    "Witches/Wizards": "\\bwitcheswizardss?\\b",
    "Zombies": "\\bzombiess?\\b",
    "Other": "\\bothers?\\b"
  },
  "toe-style": {
    "Almond": "\\balmonds?\\b",
    "Cap": "\\bcaps?\\b",
    "Moc": "\\bmocs?\\b",
    "Open": "\\bopens?\\b",
    "Peep": "\\bpeeps?\\b",
    "Pointed": "\\bpointeds?\\b",
    "Round": "\\brounds?\\b",
    "Square": "\\bsquares?\\b",
    "Wingtip": "\\bwingtips?\\b",
    "Other": "\\bothers?\\b"
  },
  "watch-display": {
    "Ana-Digi": "\\banadigis?\\b",
    "Analog": "\\banalogs?\\b",
    "Digital": "\\bdigitals?\\b",
    "Other": "\\bothers?\\b"
  },
  "baby-toddler-hosiery-style": {
    "Ankle socks": "\\bankle[\\s\\-]?sockss?\\b",
    "Crew socks": "\\bcrew[\\s\\-]?sockss?\\b",
    "Knee-high socks": "\\bkneehigh[\\s\\-]?sockss?\\b",
    "Pantyhose": "\\bpantyhoses?\\b",
    "Tights": "\\btightss?\\b"
  },
  "sandal-style": {
    "Ankle strap": "\\bankle[\\s\\-]?straps?\\b",
    "Clogs": "\\bclogss?\\b",
    "Comfort": "\\bcomforts?\\b",
    "Fisherman": "\\bfishermans?\\b",
    "Flip-flop": "\\bflipflops?\\b",
    "Gladiator": "\\bgladiators?\\b",
    "Huarache": "\\bhuaraches?\\b",
    "Lace-up": "\\blaceups?\\b",
    "Mule flat": "\\bmule[\\s\\-]?flats?\\b",
    "Slide": "\\bslides?\\b",
    "Slingback": "\\bslingbacks?\\b",
    "T-strap": "\\btstraps?\\b",
    "Thong": "\\bthongs?\\b",
    "Toe ring": "\\btoe[\\s\\-]?rings?\\b",
    "Other": "\\bothers?\\b"
  },
  "heel-shoe-type": {
    "Ankle-strap d'Orsay": "\\banklestrap[\\s\\-]?dorsays?\\b",
    "Ankle-strap pumps": "\\banklestrap[\\s\\-]?pumpss?\\b",
    "Brogues heels": "\\bbrogues[\\s\\-]?heelss?\\b",
    "Classic d'Orsay": "\\bclassic[\\s\\-]?dorsays?\\b",
    "Classic pumps": "\\bclassic[\\s\\-]?pumpss?\\b",
    "Loafer pumps": "\\bloafer[\\s\\-]?pumpss?\\b",
    "Mary-Jane heels": "\\bmaryjane[\\s\\-]?heelss?\\b",
    "Mule heels": "\\bmule[\\s\\-]?heelss?\\b",
    "Oxford heels": "\\boxford[\\s\\-]?heelss?\\b",
    "Platform heels": "\\bplatform[\\s\\-]?heelss?\\b",
    "Slingback d'Orsay": "\\bslingback[\\s\\-]?dorsays?\\b",
    "Slingback heels": "\\bslingback[\\s\\-]?heelss?\\b",
    "T-strap d'Orsay": "\\btstrap[\\s\\-]?dorsays?\\b",
    "T-strap pumps": "\\btstrap[\\s\\-]?pumpss?\\b",
    "Wedge heels": "\\bwedge[\\s\\-]?heelss?\\b",
    "Other": "\\bothers?\\b"
  },
  "shoe-features": {
    "Anti-microbial": "\\bantimicrobials?\\b",
    "Arch support": "\\barch[\\s\\-]?supports?\\b",
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Cushioned": "\\bcushioneds?\\b",
    "Eco friendly": "\\beco[\\s\\-]?friendlys?\\b",
    "Lightweight": "\\blightweights?\\b",
    "Orthopedic": "\\borthopedics?\\b",
    "Recycled materials": "\\brecycled[\\s\\-]?materialss?\\b",
    "Slip resistant": "\\bslip[\\s\\-]?resistants?\\b",
    "Sustainable sourcing": "\\bsustainable[\\s\\-]?sourcings?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "Other": "\\bothers?\\b"
  },
  "handwear-type": {
    "Arm gloves": "\\barm[\\s\\-]?glovess?\\b",
    "Convertible mittens": "\\bconvertible[\\s\\-]?mittenss?\\b",
    "Fingerless gloves": "\\bfingerless[\\s\\-]?glovess?\\b",
    "Gloves": "\\bglovess?\\b",
    "Mittens": "\\bmittenss?\\b",
    "Snow gloves": "\\bsnow[\\s\\-]?glovess?\\b",
    "Other": "\\bothers?\\b"
  },
  "shape": {
    "Arrow": "\\barrows?\\b",
    "Conical": "\\bconicals?\\b",
    "Custom": "\\bcustoms?\\b",
    "Cylindrical": "\\bcylindricals?\\b",
    "Diamond": "\\bdiamonds?\\b",
    "Flower": "\\bflowers?\\b",
    "Free-form": "\\bfreeforms?\\b",
    "Heart": "\\bhearts?\\b",
    "Heptagonal": "\\bheptagonals?\\b",
    "Hexagonal": "\\bhexagonals?\\b",
    "Kidney-shaped": "\\bkidneyshapeds?\\b",
    "Octagonal": "\\boctagonals?\\b",
    "Oval": "\\bovals?\\b",
    "Pentagonal": "\\bpentagonals?\\b",
    "Rectangular": "\\brectangulars?\\b",
    "Round": "\\brounds?\\b",
    "Semicircular": "\\bsemicirculars?\\b",
    "Square": "\\bsquares?\\b",
    "Star": "\\bstars?\\b",
    "Trapezoidal": "\\btrapezoidals?\\b",
    "Triangular": "\\btriangulars?\\b",
    "Other": "\\bothers?\\b"
  },
  "neckline": {
    "Asymmetric": "\\basymmetrics?\\b",
    "Bardot": "\\bbardots?\\b",
    "Boat": "\\bboats?\\b",
    "Cowl": "\\bcowls?\\b",
    "Crew": "\\bcrews?\\b",
    "Halter": "\\bhalters?\\b",
    "Hooded": "\\bhoodeds?\\b",
    "Mandarin": "\\bmandarins?\\b",
    "Mock": "\\bmocks?\\b",
    "Plunging": "\\bplungings?\\b",
    "Round": "\\brounds?\\b",
    "Split": "\\bsplits?\\b",
    "Square": "\\bsquares?\\b",
    "Sweetheart": "\\bsweethearts?\\b",
    "Turtle": "\\bturtles?\\b",
    "V-neck": "\\bvnecks?\\b",
    "Wrap": "\\bwraps?\\b",
    "Other": "\\bothers?\\b"
  },
  "sneaker-style": {
    "Athletic": "\\bathletics?\\b",
    "Fashion": "\\bfashions?\\b",
    "High-top": "\\bhightops?\\b",
    "Low-top": "\\blowtops?\\b",
    "Slip-on": "\\bslipons?\\b",
    "Other": "\\bothers?\\b"
  },
  "best-uses": {
    "Aviation": "\\baviations?\\b",
    "Cruising": "\\bcruisings?\\b",
    "Cycling": "\\bcyclings?\\b",
    "Diving": "\\bdivings?\\b",
    "Fishing": "\\bfishings?\\b",
    "Hiking": "\\bhikings?\\b",
    "Lifestyle": "\\blifestyles?\\b",
    "Maritime activities": "\\bmaritime[\\s\\-]?activitiess?\\b",
    "Motorcycling": "\\bmotorcyclings?\\b",
    "Navigation": "\\bnavigations?\\b",
    "Racing": "\\bracings?\\b",
    "Running": "\\brunnings?\\b",
    "Safety": "\\bsafetys?\\b",
    "Sailing": "\\bsailings?\\b",
    "Sport": "\\bsports?\\b",
    "Traveling": "\\btravelings?\\b",
    "Water sports": "\\bwater[\\s\\-]?sportss?\\b",
    "Other": "\\bothers?\\b"
  },
  "eyewear-frame-design": {
    "Aviator": "\\baviators?\\b",
    "Cat-eye": "\\bcateyes?\\b",
    "Rectangle": "\\brectangles?\\b",
    "Round": "\\brounds?\\b",
    "Wayfarer": "\\bwayfarers?\\b",
    "Other": "\\bothers?\\b"
  },
  "nightgown-style": {
    "Babydoll": "\\bbabydolls?\\b",
    "Chemise": "\\bchemises?\\b",
    "Other": "\\bothers?\\b"
  },
  "bra-closure-type": {
    "Back": "\\bbacks?\\b",
    "Front": "\\bfronts?\\b",
    "Pull-on (no closure)": "\\bpullon[\\s\\-]?no[\\s\\-]?closures?\\b",
    "Other": "\\bothers?\\b"
  },
  "carry-options": {
    "Backpack strap": "\\bbackpack[\\s\\-]?straps?\\b",
    "Belt loops": "\\bbelt[\\s\\-]?loopss?\\b",
    "Chest/Waist strap": "\\bchestwaist[\\s\\-]?straps?\\b",
    "Crossbody strap": "\\bcrossbody[\\s\\-]?straps?\\b",
    "Detachable strap": "\\bdetachable[\\s\\-]?straps?\\b",
    "Handle": "\\bhandles?\\b",
    "Shoulder strap": "\\bshoulder[\\s\\-]?straps?\\b",
    "Stroller strap": "\\bstroller[\\s\\-]?straps?\\b",
    "Trolley sleeve": "\\btrolley[\\s\\-]?sleeves?\\b",
    "Other": "\\bothers?\\b"
  },
  "chain-link-type": {
    "Ball/Bead": "\\bballbeads?\\b",
    "Byzantine/Birdcage": "\\bbyzantinebirdcages?\\b",
    "Cable": "\\bcables?\\b",
    "Figaro": "\\bfigaros?\\b",
    "Flat": "\\bflats?\\b",
    "Foxtail": "\\bfoxtails?\\b",
    "Franco": "\\bfrancos?\\b",
    "Gourmette/Curb": "\\bgourmettecurbs?\\b",
    "Heart": "\\bhearts?\\b",
    "Herringbone": "\\bherringbones?\\b",
    "Infinity": "\\binfinitys?\\b",
    "Marine/Anchor": "\\bmarineanchors?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Omega": "\\bomegas?\\b",
    "Popcorn/Coreana": "\\bpopcorncoreanas?\\b",
    "Rolo/Belcher": "\\brolobelchers?\\b",
    "Rope": "\\bropes?\\b",
    "Round": "\\brounds?\\b",
    "Serpentine": "\\bserpentines?\\b",
    "Singapore": "\\bsingapores?\\b",
    "Snake": "\\bsnakes?\\b",
    "Trace": "\\btraces?\\b",
    "Twisted curb": "\\btwisted[\\s\\-]?curbs?\\b",
    "Venetian": "\\bvenetians?\\b",
    "Wheat/Espiga": "\\bwheatespigas?\\b",
    "Other": "\\bothers?\\b"
  },
  "slipper-style": {
    "Ballerina": "\\bballerinas?\\b",
    "Bootie": "\\bbooties?\\b",
    "Clog": "\\bclogs?\\b",
    "Espadrille": "\\bespadrilles?\\b",
    "Flip-flop": "\\bflipflops?\\b",
    "Mule": "\\bmules?\\b",
    "Scuff": "\\bscuffs?\\b",
    "Slide": "\\bslides?\\b",
    "Slipper socks": "\\bslipper[\\s\\-]?sockss?\\b",
    "Other": "\\bothers?\\b"
  },
  "flat-shoe-style": {
    "Ballet": "\\bballets?\\b",
    "Boat shoe": "\\bboat[\\s\\-]?shoes?\\b",
    "Brogues": "\\bbroguess?\\b",
    "Crib shoe": "\\bcrib[\\s\\-]?shoes?\\b",
    "D'Orsay": "\\bdorsays?\\b",
    "Espadrilles": "\\bespadrilless?\\b",
    "Mary-Jane": "\\bmaryjanes?\\b",
    "Moccasins": "\\bmoccasinss?\\b",
    "Monk strap": "\\bmonk[\\s\\-]?straps?\\b",
    "Mule": "\\bmules?\\b",
    "Oxford": "\\boxfords?\\b",
    "Slingback": "\\bslingbacks?\\b",
    "Other": "\\bothers?\\b"
  },
  "ring-design": {
    "Band": "\\bbands?\\b",
    "Beaded": "\\bbeadeds?\\b",
    "Birthstone": "\\bbirthstones?\\b",
    "Chain": "\\bchains?\\b",
    "Charm": "\\bcharms?\\b",
    "Claddagh": "\\bcladdaghs?\\b",
    "Cocktail": "\\bcocktails?\\b",
    "Cuff": "\\bcuffs?\\b",
    "Eternity": "\\beternitys?\\b",
    "Halo": "\\bhalos?\\b",
    "Row": "\\brows?\\b",
    "Signet": "\\bsignets?\\b",
    "Solitaire": "\\bsolitaires?\\b",
    "Stackable": "\\bstackables?\\b",
    "Tennis": "\\btenniss?\\b",
    "Three-stone": "\\bthreestones?\\b",
    "Other": "\\bothers?\\b"
  },
  "bracelet-design": {
    "Bangle": "\\bbangles?\\b",
    "Beaded": "\\bbeadeds?\\b",
    "Chain": "\\bchains?\\b",
    "Charm": "\\bcharms?\\b",
    "Cord": "\\bcords?\\b",
    "Cuff": "\\bcuffs?\\b",
    "Friendship": "\\bfriendships?\\b",
    "Link": "\\blinks?\\b",
    "Slider": "\\bsliders?\\b",
    "Tennis": "\\btenniss?\\b",
    "Woven beaded": "\\bwoven[\\s\\-]?beadeds?\\b",
    "Wrap": "\\bwraps?\\b",
    "Other": "\\bothers?\\b"
  },
  "body-jewelry-type": {
    "Barbell": "\\bbarbells?\\b",
    "Belly piercing": "\\bbelly[\\s\\-]?piercings?\\b",
    "Body chain": "\\bbody[\\s\\-]?chains?\\b",
    "Cartilage earring": "\\bcartilage[\\s\\-]?earrings?\\b",
    "Dermal piercing": "\\bdermal[\\s\\-]?piercings?\\b",
    "Ear cuff": "\\bear[\\s\\-]?cuffs?\\b",
    "Ear gauge": "\\bear[\\s\\-]?gauges?\\b",
    "Eyebrow piercing": "\\beyebrow[\\s\\-]?piercings?\\b",
    "Industrial piercing": "\\bindustrial[\\s\\-]?piercings?\\b",
    "Labret piercing": "\\blabret[\\s\\-]?piercings?\\b",
    "Lip ring": "\\blip[\\s\\-]?rings?\\b",
    "Nipple ring": "\\bnipple[\\s\\-]?rings?\\b",
    "Nose piercing": "\\bnose[\\s\\-]?piercings?\\b",
    "Septum ring": "\\bseptum[\\s\\-]?rings?\\b",
    "Tongue piercing": "\\btongue[\\s\\-]?piercings?\\b",
    "Tragus earring": "\\btragus[\\s\\-]?earrings?\\b",
    "Other": "\\bothers?\\b"
  },
  "baby-toddler-hat-style": {
    "Baseball cap": "\\bbaseball[\\s\\-]?caps?\\b",
    "Beanie": "\\bbeanies?\\b",
    "Bonnet": "\\bbonnets?\\b",
    "Bucket hat": "\\bbucket[\\s\\-]?hats?\\b",
    "Sun hat": "\\bsun[\\s\\-]?hats?\\b"
  },
  "necklace-design": {
    "Beaded": "\\bbeadeds?\\b",
    "Chain": "\\bchains?\\b",
    "Choker": "\\bchokers?\\b",
    "Cord": "\\bcords?\\b",
    "Cuff": "\\bcuffs?\\b",
    "Lariat": "\\blariats?\\b",
    "Pendant": "\\bpendants?\\b",
    "Riviera": "\\brivieras?\\b",
    "Statement": "\\bstatements?\\b",
    "Strand": "\\bstrands?\\b",
    "Y-shaped": "\\byshapeds?\\b",
    "Other": "\\bothers?\\b"
  },
  "color": {
    "Beige": "\\bbeiges?\\b",
    "Black": "\\bblacks?\\b",
    "Blue": "\\bblues?\\b",
    "Bronze": "\\bbronzes?\\b",
    "Brown": "\\bbrowns?\\b",
    "Clear": "\\bclears?\\b",
    "Gold": "\\bgolds?\\b",
    "Gray": "\\bgrays?\\b",
    "Green": "\\bgreens?\\b",
    "Multicolor": "\\bmulticolors?\\b",
    "Navy": "\\bnavys?\\b",
    "Orange": "\\boranges?\\b",
    "Pink": "\\bpinks?\\b",
    "Purple": "\\bpurples?\\b",
    "Red": "\\breds?\\b",
    "Rose gold": "\\brose[\\s\\-]?golds?\\b",
    "Silver": "\\bsilvers?\\b",
    "White": "\\bwhites?\\b",
    "Yellow": "\\byellows?\\b"
  },
  "boot-style": {
    "Biker": "\\bbikers?\\b",
    "Boot": "\\bboots?\\b",
    "Booties": "\\bbootiess?\\b",
    "Chelsea": "\\bchelseas?\\b",
    "Chukka": "\\bchukkas?\\b",
    "Classic": "\\bclassics?\\b",
    "Combat": "\\bcombats?\\b",
    "Cowboy": "\\bcowboys?\\b",
    "Cut-out": "\\bcutouts?\\b",
    "Duck": "\\bducks?\\b",
    "Hiking": "\\bhikings?\\b",
    "Indian": "\\bindians?\\b",
    "Rain": "\\brains?\\b",
    "Riding": "\\bridings?\\b",
    "Sheepskin": "\\bsheepskins?\\b",
    "Slouch": "\\bslouchs?\\b",
    "Snow": "\\bsnows?\\b",
    "Sock": "\\bsocks?\\b",
    "Strap": "\\bstraps?\\b",
    "Winter": "\\bwinters?\\b",
    "Work": "\\bworks?\\b",
    "Other": "\\bothers?\\b"
  },
  "underwear-style": {
    "Bikini panties": "\\bbikini[\\s\\-]?pantiess?\\b",
    "Boxer briefs": "\\bboxer[\\s\\-]?briefss?\\b",
    "Boxers": "\\bboxerss?\\b",
    "Boyshorts": "\\bboyshortss?\\b",
    "Classic briefs": "\\bclassic[\\s\\-]?briefss?\\b",
    "Control briefs": "\\bcontrol[\\s\\-]?briefss?\\b",
    "G-string panties": "\\bgstring[\\s\\-]?pantiess?\\b",
    "High-cut briefs": "\\bhighcut[\\s\\-]?briefss?\\b",
    "Hipster panties": "\\bhipster[\\s\\-]?pantiess?\\b",
    "Raw-cut briefs": "\\brawcut[\\s\\-]?briefss?\\b",
    "Tanga panties": "\\btanga[\\s\\-]?pantiess?\\b",
    "Thong panties": "\\bthong[\\s\\-]?pantiess?\\b",
    "Trunk": "\\btrunks?\\b",
    "Other": "\\bothers?\\b"
  },
  "dress-occasion": {
    "Birthday": "\\bbirthdays?\\b",
    "Casual": "\\bcasuals?\\b",
    "Dance": "\\bdances?\\b",
    "Everyday": "\\beverydays?\\b",
    "Formal": "\\bformals?\\b",
    "Holiday": "\\bholidays?\\b",
    "Pageant": "\\bpageants?\\b",
    "Party": "\\bpartys?\\b",
    "Portrait": "\\bportraits?\\b",
    "Religious ceremony": "\\breligious[\\s\\-]?ceremonys?\\b",
    "School": "\\bschools?\\b",
    "Wedding": "\\bweddings?\\b",
    "Other": "\\bothers?\\b"
  },
  "scarf-shawl-style": {
    "Blanket": "\\bblankets?\\b",
    "Cowl": "\\bcowls?\\b",
    "Cravat": "\\bcravats?\\b",
    "Fur": "\\bfurs?\\b",
    "Infinity": "\\binfinitys?\\b",
    "Pashmina": "\\bpashminas?\\b",
    "Regular": "\\bregulars?\\b",
    "Shawl": "\\bshawls?\\b",
    "Sport": "\\bsports?\\b",
    "Square": "\\bsquares?\\b",
    "Wrap": "\\bwraps?\\b"
  },
  "bristle-material": {
    "Boar bristle": "\\bboar[\\s\\-]?bristles?\\b",
    "Cotton": "\\bcottons?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Horsehair": "\\bhorsehairs?\\b",
    "Leather": "\\bleathers?\\b",
    "Linen": "\\blinens?\\b",
    "Metal": "\\bmetals?\\b",
    "Microfiber": "\\bmicrofibers?\\b",
    "Natural bristle": "\\bnatural[\\s\\-]?bristles?\\b",
    "Nylon": "\\bnylons?\\b",
    "Plastic": "\\bplastics?\\b",
    "Polypropylene (PP)": "\\bpolypropylene[\\s\\-]?pps?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Rubber": "\\brubbers?\\b",
    "Silicone": "\\bsilicones?\\b",
    "Stainless steel": "\\bstainless[\\s\\-]?steels?\\b",
    "Synthetic bristle": "\\bsynthetic[\\s\\-]?bristles?\\b",
    "Teflon": "\\bteflons?\\b",
    "Wood": "\\bwoods?\\b",
    "Other": "\\bothers?\\b"
  },
  "top-length-type": {
    "Bodysuit": "\\bbodysuits?\\b",
    "Crop top": "\\bcrop[\\s\\-]?tops?\\b",
    "Long": "\\blongs?\\b",
    "Medium": "\\bmediums?\\b",
    "Other": "\\bothers?\\b"
  },
  "one-piece-style": {
    "Bodysuit": "\\bbodysuits?\\b",
    "Boiler suit": "\\bboiler[\\s\\-]?suits?\\b",
    "Catsuit": "\\bcatsuits?\\b",
    "Coverall": "\\bcoveralls?\\b",
    "Dungaree": "\\bdungarees?\\b",
    "Jumpsuit": "\\bjumpsuits?\\b",
    "Leotard": "\\bleotards?\\b",
    "Overall": "\\boveralls?\\b",
    "Playsuit": "\\bplaysuits?\\b",
    "Romper": "\\brompers?\\b",
    "Salopette": "\\bsalopettes?\\b",
    "Unitard": "\\bunitards?\\b",
    "Other": "\\bothers?\\b"
  },
  "fit": {
    "Boyfriend": "\\bboyfriends?\\b",
    "Mom": "\\bmoms?\\b",
    "Skinny leg": "\\bskinny[\\s\\-]?legs?\\b",
    "Slim": "\\bslims?\\b",
    "Straight leg": "\\bstraight[\\s\\-]?legs?\\b",
    "Tapered leg": "\\btapered[\\s\\-]?legs?\\b",
    "Wide": "\\bwides?\\b",
    "Other": "\\bothers?\\b"
  },
  "skirt-style": {
    "Bracer": "\\bbracers?\\b",
    "Circle": "\\bcircles?\\b",
    "Denim": "\\bdenims?\\b",
    "Gathered": "\\bgathereds?\\b",
    "Kilt": "\\bkilts?\\b",
    "Layered": "\\blayereds?\\b",
    "Pencil": "\\bpencils?\\b",
    "Pleated": "\\bpleateds?\\b",
    "Plisse": "\\bplisses?\\b",
    "Prairie": "\\bprairies?\\b",
    "Sheath": "\\bsheaths?\\b",
    "Skirtall": "\\bskirtalls?\\b",
    "Tailored": "\\btailoreds?\\b",
    "Tutu": "\\btutus?\\b",
    "Wrap": "\\bwraps?\\b",
    "Other": "\\bothers?\\b"
  },
  "outerwear-clothing-features": {
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Hooded": "\\bhoodeds?\\b",
    "Hypoallergenic": "\\bhypoallergenics?\\b",
    "Insulated": "\\binsulateds?\\b",
    "Lightweight": "\\blightweights?\\b",
    "Pockets": "\\bpocketss?\\b",
    "Quick drying": "\\bquick[\\s\\-]?dryings?\\b",
    "Thermal": "\\bthermals?\\b",
    "UV protection": "\\buv[\\s\\-]?protections?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "Windproof": "\\bwindproofs?\\b",
    "Wrinkle resistant": "\\bwrinkle[\\s\\-]?resistants?\\b",
    "Other": "\\bothers?\\b"
  },
  "intimate-apparel-features": {
    "Breathable design": "\\bbreathable[\\s\\-]?designs?\\b",
    "Comfort fit": "\\bcomfort[\\s\\-]?fits?\\b",
    "Hypoallergenic": "\\bhypoallergenics?\\b",
    "Moisture wicking": "\\bmoisture[\\s\\-]?wickings?\\b",
    "Seamless": "\\bseamlesss?\\b",
    "Stretchable": "\\bstretchables?\\b",
    "Tagless": "\\btaglesss?\\b",
    "Thermal": "\\bthermals?\\b",
    "Other": "\\bothers?\\b"
  },
  "clasp-type": {
    "Buckle": "\\bbuckles?\\b",
    "Butterfly": "\\bbutterflys?\\b",
    "Deployment": "\\bdeployments?\\b",
    "Other": "\\bothers?\\b"
  },
  "bag-closure": {
    "Buckles": "\\bbuckless?\\b",
    "Button": "\\bbuttons?\\b",
    "Clip": "\\bclips?\\b",
    "Combination lock": "\\bcombination[\\s\\-]?locks?\\b",
    "Drawstring": "\\bdrawstrings?\\b",
    "Elastic": "\\belastics?\\b",
    "Flap": "\\bflaps?\\b",
    "Hook & loop": "\\bhook[\\s\\-]?[\\s\\-]?loops?\\b",
    "Key lock": "\\bkey[\\s\\-]?locks?\\b",
    "Latch": "\\blatchs?\\b",
    "Magnetic": "\\bmagnetics?\\b",
    "Open top": "\\bopen[\\s\\-]?tops?\\b",
    "Push lock": "\\bpush[\\s\\-]?locks?\\b",
    "Roll-top": "\\brolltops?\\b",
    "Snap": "\\bsnaps?\\b",
    "Toggle": "\\btoggles?\\b",
    "Twist lock": "\\btwist[\\s\\-]?locks?\\b",
    "Velcro": "\\bvelcros?\\b",
    "Zipper": "\\bzippers?\\b",
    "Other": "\\bothers?\\b"
  },
  "clothing-accessory-material": {
    "Burlap": "\\bburlaps?\\b",
    "Canvas": "\\bcanvass?\\b",
    "Cotton": "\\bcottons?\\b",
    "Denim": "\\bdenims?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Felt": "\\bfelts?\\b",
    "Fleece": "\\bfleeces?\\b",
    "Foam": "\\bfoams?\\b",
    "Leather": "\\bleathers?\\b",
    "Linen": "\\blinens?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Metal": "\\bmetals?\\b",
    "Microfiber": "\\bmicrofibers?\\b",
    "Nylon": "\\bnylons?\\b",
    "Plastic": "\\bplastics?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polyurethane (PU)": "\\bpolyurethane[\\s\\-]?pus?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Rubber": "\\brubbers?\\b",
    "Satin": "\\bsatins?\\b",
    "Silicone": "\\bsilicones?\\b",
    "Silk": "\\bsilks?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Tweed": "\\btweeds?\\b",
    "Velvet": "\\bvelvets?\\b",
    "Vinyl": "\\bvinyls?\\b",
    "Wood": "\\bwoods?\\b",
    "Wool": "\\bwools?\\b",
    "Other": "\\bothers?\\b"
  },
  "footwear-material": {
    "Canvas": "\\bcanvass?\\b",
    "Cotton": "\\bcottons?\\b",
    "Faux fur": "\\bfaux[\\s\\-]?furs?\\b",
    "Faux leather": "\\bfaux[\\s\\-]?leathers?\\b",
    "Fleece": "\\bfleeces?\\b",
    "Leather": "\\bleathers?\\b",
    "Linen": "\\blinens?\\b",
    "Mesh": "\\bmeshs?\\b",
    "Neoprene": "\\bneoprenes?\\b",
    "Nylon": "\\bnylons?\\b",
    "Plastic": "\\bplastics?\\b",
    "Polyester": "\\bpolyesters?\\b",
    "Polyvinyl chloride (PVC)": "\\bpolyvinyl[\\s\\-]?chloride[\\s\\-]?pvcs?\\b",
    "Rubber": "\\brubbers?\\b",
    "Satin": "\\bsatins?\\b",
    "Silk": "\\bsilks?\\b",
    "Spandex": "\\bspandexs?\\b",
    "Suede": "\\bsuedes?\\b",
    "Synthetic": "\\bsynthetics?\\b",
    "Thermoplastic polyurethane (TPU)": "\\bthermoplastic[\\s\\-]?polyurethane[\\s\\-]?tpus?\\b",
    "Wool": "\\bwools?\\b",
    "Other": "\\bothers?\\b"
  },
  "wallet-features": {
    "Card organization": "\\bcard[\\s\\-]?organizations?\\b",
    "Compact design": "\\bcompact[\\s\\-]?designs?\\b",
    "RFID protection": "\\brfid[\\s\\-]?protections?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Waterproof": "\\bwaterproofs?\\b",
    "Other": "\\bothers?\\b"
  },
  "occasion-style": {
    "Casual": "\\bcasuals?\\b",
    "Dress": "\\bdresss?\\b",
    "Other": "\\bothers?\\b"
  },
  "earring-design": {
    "Chandelier": "\\bchandeliers?\\b",
    "Clip-On": "\\bclipons?\\b",
    "Dangle": "\\bdangles?\\b",
    "Drop": "\\bdrops?\\b",
    "Ear climber": "\\bear[\\s\\-]?climbers?\\b",
    "Ear cuff": "\\bear[\\s\\-]?cuffs?\\b",
    "Hoop": "\\bhoops?\\b",
    "Huggie": "\\bhuggies?\\b",
    "Jacket": "\\bjackets?\\b",
    "Stud": "\\bstuds?\\b",
    "Teardrop": "\\bteardrops?\\b",
    "Threader": "\\bthreaders?\\b",
    "Other": "\\bothers?\\b"
  },
  "watch-accessory-style": {
    "Classic": "\\bclassics?\\b",
    "Modern": "\\bmoderns?\\b",
    "Sporty": "\\bsportys?\\b",
    "Other": "\\bothers?\\b"
  },
  "attachment-options": {
    "Clip": "\\bclips?\\b",
    "Lanyard": "\\blanyards?\\b",
    "Magnet": "\\bmagnets?\\b",
    "Pin": "\\bpins?\\b",
    "Other": "\\bothers?\\b"
  },
  "accessory-size": {
    "Compact": "\\bcompacts?\\b",
    "Customizable": "\\bcustomizables?\\b",
    "Double extra large (XXL)": "\\bdouble[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?xxls?\\b",
    "Double extra small (XXS)": "\\bdouble[\\s\\-]?extra[\\s\\-]?small[\\s\\-]?xxss?\\b",
    "Extra large (XL)": "\\bextra[\\s\\-]?large[\\s\\-]?xls?\\b",
    "Extra long": "\\bextra[\\s\\-]?longs?\\b",
    "Extra short": "\\bextra[\\s\\-]?shorts?\\b",
    "Extra small (XS)": "\\bextra[\\s\\-]?small[\\s\\-]?xss?\\b",
    "Five extra large (5XL)": "\\bfive[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?5xls?\\b",
    "Four extra large (4XL)": "\\bfour[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?4xls?\\b",
    "Large (L)": "\\blarge[\\s\\-]?ls?\\b",
    "Long": "\\blongs?\\b",
    "Medium (M)": "\\bmedium[\\s\\-]?ms?\\b",
    "One size": "\\bone[\\s\\-]?sizes?\\b",
    "Regular (R)": "\\bregular[\\s\\-]?rs?\\b",
    "Short": "\\bshorts?\\b",
    "Six extra large (6XL)": "\\bsix[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?6xls?\\b",
    "Small (S)": "\\bsmall[\\s\\-]?ss?\\b",
    "Standard": "\\bstandards?\\b",
    "Travel size": "\\btravel[\\s\\-]?sizes?\\b",
    "Triple extra large (XXXL)": "\\btriple[\\s\\-]?extra[\\s\\-]?large[\\s\\-]?xxxls?\\b",
    "Triple extra small (XXXS)": "\\btriple[\\s\\-]?extra[\\s\\-]?small[\\s\\-]?xxxss?\\b",
    "Other": "\\bothers?\\b"
  },
  "pantyhose-style": {
    "Compression": "\\bcompressions?\\b",
    "Control-top": "\\bcontroltops?\\b",
    "Fishnet": "\\bfishnets?\\b",
    "Footless": "\\bfootlesss?\\b",
    "Maternity": "\\bmaternitys?\\b",
    "Opaque": "\\bopaques?\\b",
    "Seamed": "\\bseameds?\\b",
    "Sheer": "\\bsheers?\\b",
    "Toeless": "\\btoelesss?\\b",
    "Other": "\\bothers?\\b"
  },
  "first-steps-crawlers-style": {
    "Crawling shoes": "\\bcrawling[\\s\\-]?shoess?\\b",
    "First walkers": "\\bfirst[\\s\\-]?walkerss?\\b",
    "Pre-walkers": "\\bprewalkerss?\\b",
    "Soft sole shoes": "\\bsoft[\\s\\-]?sole[\\s\\-]?shoess?\\b"
  },
  "undershirt-style": {
    "Crew neck": "\\bcrew[\\s\\-]?necks?\\b",
    "Long sleeved": "\\blong[\\s\\-]?sleeveds?\\b",
    "Sleeveless": "\\bsleevelesss?\\b",
    "Thermal": "\\bthermals?\\b",
    "V-neck": "\\bvnecks?\\b",
    "Other": "\\bothers?\\b"
  },
  "hair-type": {
    "Curly": "\\bcurlys?\\b",
    "Dry": "\\bdrys?\\b",
    "Normal": "\\bnormals?\\b",
    "Straight": "\\bstraights?\\b",
    "Wavy": "\\bwavys?\\b",
    "Other": "\\bothers?\\b"
  },
  "bra-coverage": {
    "Demi": "\\bdemis?\\b",
    "Full": "\\bfulls?\\b",
    "Minimal": "\\bminimals?\\b",
    "Plunge": "\\bplunges?\\b",
    "Quarter": "\\bquarters?\\b",
    "Other": "\\bothers?\\b"
  },
  "usage-type": {
    "Disposable": "\\bdisposables?\\b",
    "Refillable": "\\brefillables?\\b",
    "Reusable": "\\breusables?\\b",
    "Other": "\\bothers?\\b"
  },
  "care-instructions": {
    "Dry clean only": "\\bdry[\\s\\-]?clean[\\s\\-]?onlys?\\b",
    "Dryer safe": "\\bdryer[\\s\\-]?safes?\\b",
    "Hand wash": "\\bhand[\\s\\-]?washs?\\b",
    "Ironing instructions": "\\bironing[\\s\\-]?instructionss?\\b",
    "Machine washable": "\\bmachine[\\s\\-]?washables?\\b",
    "Tumble dry": "\\btumble[\\s\\-]?drys?\\b",
    "Other": "\\bothers?\\b"
  },
  "target-gender": {
    "Female": "\\bfemales?\\b",
    "Male": "\\bmales?\\b",
    "Unisex": "\\bunisexs?\\b",
    "Other": "\\bothers?\\b"
  },
  "jewelry-type": {
    "Fine jewelry": "\\bfine[\\s\\-]?jewelrys?\\b",
    "Imitation jewelry": "\\bimitation[\\s\\-]?jewelrys?\\b",
    "Other": "\\bothers?\\b"
  },
  "heel-height-type": {
    "Flat": "\\bflats?\\b",
    "High": "\\bhighs?\\b",
    "Low": "\\blows?\\b",
    "Mid": "\\bmids?\\b",
    "Very high": "\\bvery[\\s\\-]?highs?\\b",
    "Other": "\\bothers?\\b"
  },
  "baby-toddler-sleepwear-style": {
    "Footed": "\\bfooteds?\\b",
    "Nightgown": "\\bnightgowns?\\b",
    "Onesie": "\\bonesies?\\b",
    "Sleep sack": "\\bsleep[\\s\\-]?sacks?\\b",
    "Two-piece": "\\btwopieces?\\b"
  },
  "absorbency-level": {
    "Heavy": "\\bheavys?\\b",
    "Light": "\\blights?\\b",
    "Moderate": "\\bmoderates?\\b",
    "Overnight": "\\bovernights?\\b",
    "Regular": "\\bregulars?\\b",
    "Super": "\\bsupers?\\b",
    "Other": "\\bothers?\\b"
  },
  "waist-rise": {
    "High": "\\bhighs?\\b",
    "Low": "\\blows?\\b",
    "Mid": "\\bmids?\\b",
    "Other": "\\bothers?\\b"
  },
  "bra-support-level": {
    "High": "\\bhighs?\\b",
    "Low": "\\blows?\\b",
    "Medium": "\\bmediums?\\b",
    "Other": "\\bothers?\\b"
  },
  "clothing-features": {
    "Hypoallergenic": "\\bhypoallergenics?\\b",
    "Insulated": "\\binsulateds?\\b",
    "Moisture wicking": "\\bmoisture[\\s\\-]?wickings?\\b",
    "Quick drying": "\\bquick[\\s\\-]?dryings?\\b",
    "Reversible": "\\breversibles?\\b",
    "Stretchable": "\\bstretchables?\\b",
    "UV protection": "\\buv[\\s\\-]?protections?\\b",
    "Vegan friendly": "\\bvegan[\\s\\-]?friendlys?\\b",
    "Water resistant": "\\bwater[\\s\\-]?resistants?\\b",
    "Windproof": "\\bwindproofs?\\b",
    "Wrinkle resistant": "\\bwrinkle[\\s\\-]?resistants?\\b",
    "Other": "\\bothers?\\b"
  },
  "skirt-dress-length-type": {
    "Knee": "\\bknees?\\b",
    "Maxi": "\\bmaxis?\\b",
    "Midi": "\\bmidis?\\b",
    "Mini": "\\bminis?\\b",
    "Short": "\\bshorts?\\b"
  },
  "shapewear-support-level": {
    "Level 1": "\\blevel[\\s\\-]?1s?\\b",
    "Level 2": "\\blevel[\\s\\-]?2s?\\b",
    "Level 3": "\\blevel[\\s\\-]?3s?\\b",
    "Level 4": "\\blevel[\\s\\-]?4s?\\b",
    "Level 5": "\\blevel[\\s\\-]?5s?\\b",
    "Other": "\\bothers?\\b"
  },
  "shoe-fit": {
    "Narrow": "\\bnarrows?\\b",
    "Regular": "\\bregulars?\\b",
    "Wide": "\\bwides?\\b",
    "Other": "\\bothers?\\b"
  },
  "maternity-sleepwear-style": {
    "Nightgown": "\\bnightgowns?\\b",
    "Onesie": "\\bonesies?\\b",
    "Pajamas": "\\bpajamass?\\b",
    "Robe": "\\brobes?\\b",
    "Sleep shirt": "\\bsleep[\\s\\-]?shirts?\\b",
    "Other": "\\bothers?\\b"
  },
  "lens-polarization": {
    "Non-polarized": "\\bnonpolarizeds?\\b",
    "Photo polarized": "\\bphoto[\\s\\-]?polarizeds?\\b",
    "Polarized": "\\bpolarizeds?\\b",
    "Other": "\\bothers?\\b"
  },
  "suspender-style": {
    "X-back suspender": "\\bxback[\\s\\-]?suspenders?\\b",
    "Y-back suspender": "\\byback[\\s\\-]?suspenders?\\b",
    "Other": "\\bothers?\\b"
  }
}
